<?php
$templatenames = array (
  'area_list.html' => '地域列表模板',
  'building_search_inc.html' => '新楼房搜索模板',
  'coop_search_inc.html' => '合租搜索模板',
  'displaymgr.html' => '前台新楼市模版',
  'footer.html' => '房产页底',
  'frontmgr.html' => '房产信息管理模版',
  'header.html' => '房产头部模板',
  'header-m.html' => '发布信息头部模板',
  'house_search_inc.html' => '房源搜索模板',
  'index.html' => '房产首页模版',
  'left.html' => '发布信息左部模板',
  'listdisplay.html' => '楼盘列表信息模板',
  'listinfo.html' => '房产信息列表模版',
  'membertype.html' => '会员类型模版',
  'newhouse.html' => '楼盘内容页模版',
  'search_building.html' => '楼盘高级搜索模板',
  'search_coop.html' => '合租高级搜索模板',
  'search_house.html' => '房源高级搜索模板',
  'showinfo.html' => '房产信息内容页模版',
  'tag_display_list.html' => '楼盘列表小标签模版',
  'tag_display_list-cat.html' => '楼盘列表小标签模版2',
  'tag_display_list-scrolldisplay.html' => '楼盘滚动小标签模版',
  'tag_display_list-top.html' => '首页中部推荐房产列表',
  'tag_house_list.html' => '房产信息列表模版',
  'tag_house_list-cat.html' => '房产信息列表模版2',
  'tag_member_list.html' => '会员中介列表标签',
  'tag_member_list-name.html' => '会员中介列表标签',
  'web.html' => '中介首页',
  'web_detail.html' => '中介内容',
  'web_list.html' => '中介列表模板',
);
?>