<?php
$tags_config = array (
  '商城首页链接' => 
  array (
    'func' => 'link_list',
    'introduce' => '',
    'linktype' => '1',
    'typeid' => '0',
    'showhits' => '1',
    'linknum' => '20',
    'cols' => '2',
    'templateid' => '0',
    'edittime' => '2007-02-10 10:53:08',
    'editor' => 'phpcms',
    'longtag' => 'link_list(0,0,1,20,2,1)',
  ),
  '网站首页文字链接' => 
  array (
    'func' => 'link_list',
    'introduce' => '',
    'linktype' => '0',
    'typeid' => '0',
    'showhits' => '1',
    'linknum' => '20',
    'cols' => '2',
    'templateid' => '0',
    'edittime' => '2007-01-15 03:30:02',
    'editor' => 'phpcms',
    'longtag' => 'link_list(0,0,0,20,2,1)',
  ),
  '网站首页图片链接' => 
  array (
    'func' => 'link_list',
    'introduce' => '',
    'linktype' => '1',
    'typeid' => '0',
    'showhits' => '1',
    'linknum' => '20',
    'cols' => '2',
    'templateid' => '0',
    'edittime' => '2007-01-15 03:40:29',
    'editor' => 'phpcms',
    'longtag' => 'link_list(0,0,1,20,2,1)',
  ),
  '文章频道首页logo链接' => 
  array (
    'func' => 'link_list',
    'introduce' => '',
    'linktype' => '1',
    'typeid' => '0',
    'showhits' => '1',
    'linknum' => '10',
    'cols' => '2',
    'templateid' => '0',
    'edittime' => '2007-02-10 10:57:31',
    'editor' => 'phpcms',
    'longtag' => 'link_list(0,0,1,10,2,1)',
  ),
  '文章频道首页文字链接' => 
  array (
    'func' => 'link_list',
    'introduce' => '',
    'linktype' => '0',
    'typeid' => '0',
    'showhits' => '1',
    'linknum' => '20',
    'cols' => '2',
    'templateid' => '0',
    'edittime' => '2007-02-10 10:56:00',
    'editor' => 'phpcms',
    'longtag' => 'link_list(0,0,0,20,2,1)',
  ),
  '下载频道首页logo链接' => 
  array (
    'func' => 'link_list',
    'introduce' => '',
    'linktype' => '1',
    'typeid' => '0',
    'showhits' => '1',
    'linknum' => '10',
    'cols' => '2',
    'templateid' => '0',
    'edittime' => '2007-02-10 10:57:10',
    'editor' => 'phpcms',
    'longtag' => 'link_list(0,0,1,10,2,1)',
  ),
  '下载频道首页文字链接' => 
  array (
    'func' => 'link_list',
    'introduce' => '',
    'linktype' => '0',
    'typeid' => '0',
    'showhits' => '1',
    'linknum' => '20',
    'cols' => '2',
    'templateid' => '0',
    'edittime' => '2007-02-10 10:55:41',
    'editor' => 'phpcms',
    'longtag' => 'link_list(0,0,0,20,2,1)',
  ),
  '图片频道首页logo链接' => 
  array (
    'func' => 'link_list',
    'introduce' => '',
    'linktype' => '1',
    'typeid' => '0',
    'showhits' => '1',
    'linknum' => '10',
    'cols' => '2',
    'templateid' => '0',
    'edittime' => '2007-02-10 10:57:24',
    'editor' => 'phpcms',
    'longtag' => 'link_list(0,0,1,10,2,1)',
  ),
  '图片频道首页文字链接' => 
  array (
    'func' => 'link_list',
    'introduce' => '',
    'linktype' => '0',
    'typeid' => '0',
    'showhits' => '1',
    'linknum' => '20',
    'cols' => '2',
    'templateid' => '0',
    'edittime' => '2007-02-10 10:55:19',
    'editor' => 'phpcms',
    'longtag' => 'link_list(0,0,0,20,2,1)',
  ),
  '影片频道首页logo链接' => 
  array (
    'func' => 'link_list',
    'introduce' => '',
    'linktype' => '1',
    'typeid' => '0',
    'showhits' => '1',
    'linknum' => '10',
    'cols' => '2',
    'templateid' => '0',
    'edittime' => '2007-07-30 04:12:39',
    'editor' => 'phpcms',
    'longtag' => 'link_list(0,0,1,10,2,1)',
  ),
  '影片频道首页文字链接' => 
  array (
    'func' => 'link_list',
    'introduce' => '',
    'linktype' => '0',
    'typeid' => '0',
    'showhits' => '1',
    'linknum' => '20',
    'cols' => '2',
    'templateid' => '0',
    'edittime' => '2007-07-30 04:12:53',
    'editor' => 'phpcms',
    'longtag' => 'link_list(0,0,0,20,2,1)',
  ),
  '首页logo链接' => 
  array (
    'func' => 'link_list',
    'introduce' => '',
    'linktype' => '0',
    'typeid' => '0',
    'showhits' => '1',
    'linknum' => '20',
    'cols' => '1',
    'templateid' => '0',
    'edittime' => '2008-01-14 03:58:14',
    'editor' => 'phpcms',
    'longtag' => 'link_list(0,0,0,20,1,1)',
  ),
  '友情链接首页logo' => 
  array (
    'func' => 'link_list',
    'introduce' => '友情链接首页logo',
    'linktype' => '1',
    'typeid' => '0',
    'showhits' => '1',
    'linknum' => '20',
    'cols' => '1',
    'templateid' => 'tag_link_list-logo',
    'edittime' => '2008-01-14 04:15:28',
    'editor' => 'phpcms',
    'longtag' => 'link_list(\'tag_link_list-logo\',0,1,20,1,1)',
  ),
  '友情链接首页文字' => 
  array (
    'func' => 'link_list',
    'introduce' => '友情链接首页logo',
    'linktype' => '0',
    'typeid' => '0',
    'showhits' => '1',
    'linknum' => '20',
    'cols' => '1',
    'templateid' => 'tag_link_list-logo',
    'edittime' => '2008-01-14 04:15:49',
    'editor' => 'phpcms',
    'longtag' => 'link_list(\'tag_link_list-logo\',0,0,20,1,1)',
  ),
  '类别logo链接' => 
  array (
    'func' => 'link_list',
    'introduce' => '类别logo链接',
    'linktype' => '1',
    'typeid' => '$typeid',
    'showhits' => '1',
    'linknum' => '20',
    'cols' => '1',
    'templateid' => 'tag_link_list-logo',
    'edittime' => '2008-01-14 04:46:35',
    'editor' => 'phpcms',
    'longtag' => 'link_list(\'tag_link_list-logo\',$typeid,1,20,1,1)',
  ),
  '类别文字链接' => 
  array (
    'func' => 'link_list',
    'introduce' => '类别文字链接',
    'linktype' => '0',
    'typeid' => '$typeid',
    'showhits' => '1',
    'linknum' => '20',
    'cols' => '1',
    'templateid' => 'tag_link_list-logo',
    'edittime' => '2008-01-14 04:48:23',
    'editor' => 'phpcms',
    'longtag' => 'link_list(\'tag_link_list-logo\',$typeid,0,20,1,1)',
  ),
);
?>