<?php 
$CONFIG['dbhost'] = 'localhost'; //数据库主机
$CONFIG['dbuser'] = 'root';    //数据库用户名
$CONFIG['dbpw'] = '';  //数据库密码
$CONFIG['dbname'] = 'phpcms';  //数据库名称
$CONFIG['tablepre'] = 'phpcms_';  //数据表前缀
$CONFIG['database'] = 'mysql';  //数据库类型
$CONFIG['pconnect'] = '0';  //是否使用持久连接
$CONFIG['dbiscache'] = '0'; //是否启用 sql cache (只对前台起作用，建议在不生成html并且访问量过大时开启)
$CONFIG['dbexpires'] = '900'; //sql cache 过期时间(秒)
$CONFIG['dbcachedir'] = PHPCMS_ROOT.'/data/dbcache/';
$CONFIG['dbcharset'] = 'utf8'; //数据库连接字符集
$CONFIG['charset'] = 'utf-8'; //网站字符集
$CONFIG['rootpath'] = '/';  //phpcms安装路径（相对于网站根路径的）
$CONFIG['cachedir'] = PHPCMS_ROOT.'/data/cache/'; //总缓冲目录
$CONFIG['templatescachedir'] = PHPCMS_ROOT.'/data/templatescache/'; 
$CONFIG['phpcache'] = '0'; //是否开启缓冲功能的总开关（只对前台起作用，建议在不生成html并且访问量过大时开启）
$CONFIG['phpcacheexpires'] = '900';//缓冲过期时间(秒)
$CONFIG['cookiedomain'] = ''; //cookie 作用域
$CONFIG['cookiepath'] = '/'; //cookie 作用路径
$CONFIG['cookiepre'] = 'phpcms_'; //cookie 作用路径
$CONFIG['sessionsavepath'] = PHPCMS_ROOT.'/data/sessions/';
$CONFIG['defaulttemplate'] = 'default'; //默认模板
$CONFIG['defaultskin'] = 'default'; //默认风格
$CONFIG['templaterefresh'] = '1'; 
$CONFIG['timezone'] = 'Etc/GMT-8';  //时区设置（只对php 5.1以上版本有效），Etc/GMT-8 实际表示的是 GMT+8 
$CONFIG['debug'] = '0'; //是否显示调试信息
$CONFIG['enablephplog'] = '0'; //是否启用php错误日志
$CONFIG['enableadminlog'] = '0'; //是否启用后台操作日志
$CONFIG['language'] = 'zh-cn'; //网站前台语言
$CONFIG['adminlanguage'] = 'zh-cn'; //网站后台语言
?>