<?php
$templatenames = array (
  'category.html' => '栏目首页模版',
  'category_list.html' => '栏目列表模板',
  'content.html' => '内容页',
  'contribute.html' => '投稿页',
  'down.html' => '下载链接',
  'header.html' => '影视头部',
  'index.html' => '影视首页',
  'letter.html' => '按字母搜索页',
  'letter_list.html' => '按字母浏览列表页',
  'myitem.html' => '会员投稿',
  'play.html' => '播放窗口',
  'search.html' => '影视搜索模板',
  'special_index.html' => '专题首页',
  'special_list.html' => '专题列表页',
  'special_show.html' => '专题页',
  'tag_movie_list.html' => '影片列表',
  'tag_movie_list-no.html' => '[标签]影片列表(无地区)',
  'tag_movie_related.html' => '[标签]相关影片模板',
  'tag_movie_slide.html' => '[标签]影视幻灯片(flash)',
  'tag_movie_slide-js.html' => '[标签]影视幻灯片(js)',
  'tag_movie_slide-no.html' => '[标签]影视幻灯片(flash)无标题',
  'tag_movie_thumb.html' => '[标签]影视图片列表',
  'tag_movie_thumb-cat.html' => '[标签]栏目终极图片列表',
  'type.html' => '分类首页',
  'type_list.html' => '分类列表',
  'tag_movie_thumb-sp6photo.html' => 'sp6图片影视',
  'tag_movie_thumb-sp6.html' => '影视左右格式',
  'tag_movie_list-jr.html' => '今日影视列表',
  'tag_movie_thumb-lmtp.html' => '影视首页栏目图片',
  'tag_movie_list-zjlb.html' => 'sp6终极列表',
  'tag_movie_list-lbph.html' => '列表左边排行',
);
?>