<?php
$templatenames = array (
  'cart.html' => '购物车模板',
  'category.html' => '栏目首页',
  'category_list.html' => '栏目列表页',
  'checkaddress.html' => '订单确认收货地址模板',
  'compare.html' => '商品对比模版',
  'content.html' => '内容页模板',
  'gallery.html' => '商品图片库',
  'header.html' => '页面头部',
  'index.html' => '商城首页',
  'myorder.html' => '我的订单',
  'ordermailtpl.html' => '发送订单邮件模板',
  'payment.html' => '确认付款',
  'search.html' => '商品搜索模板',
  'showorder.html' => '订单确认模板',
  'showpay.html' => '显示付款页面',
  'tag_product_list.html' => '商品文字列表',
  'tag_product_slide.html' => '商品幻灯片',
  'tag_product_slide-flash.html' => '商品幻灯片',
  'tag_product_slidepic-js.html' => '商品JS幻灯片',
  'tag_product_thumb.html' => '图片标签默认模板',
  'tag_product_thumb-hotproduct.html' => '图片商品热门商品小模板',
  'tag_product_thumb-index.html' => '图片商品首页小模板',
  'tag_product_thumb-list.html' => '栏目内图片商品列表',
  'tag_product_thumb-new.html' => '商品图片列表小标签-2',
  'tag_product_thumb-new3.html' => '商品图片列表小标签-3',
  'vieworder.html' => '查看订单',
  'tag_product_thumb-category.html' => '终极栏目商品列表',
  'tag_product_thumb-sytpcp.html' => '首页图片产品模板',
  'tag_product_list-bt.html' => '商品列表-标题',
  'tag_product_list-rm.html' => '热卖产品列表',
  'tag_product_thumb-cpsy.html' => '产品首页小缩略图',
  'tag_product_thumb-lbmb.html' => 'sp6列表模板',
  'tag_product_thumb-cplmlb.html' => '产品栏目列表图片',
  'tag_product_thumb-sysc.html' => '首页商城',
);
?>