<?php
return array (
  'chancredit.html' => '兑换积分',
  'choice_model.html' => '注册选择类型',
  'edit.html' => '修改资料',
  'editanswer.html' => '修改找回密码问题',
  'editpwd.html' => '修改密码',
  'email.html' => '发送邮件',
  'footer.html' => '页面底部',
  'getpassword_mailcheck.html' => '邮件检测',
  'getpwd.html' => '活动密码',
  'header.html' => '页面头部',
  'index.html' => '会员中心',
  'left.html' => '会员中心左侧菜单',
  'list.html' => '用户列表',
  'login.html' => '登录页面',
  'regagreement.html' => '网站协议',
  'register.html' => '注册页面',
  'register_mailcheck.html' => '注册邮件',
  'register_model.html' => '模型注册',
  'register_notice.html' => '注册邮件提示',
  'search_index.html' => '搜索首页',
  'tag_list.html' => '[标签]会员列表',
  'tag_member.html' => '[标签]会员测试标签',
  'uc_avatar.html' => 'uc头像',
  'upgrade.html' => '等级升级',
  'upgrade_continue.html' => '等级续费',
  'upgrade_pay.html' => '等级支付',
  'upgrade_view.html' => '等级详细信息查看',
  'upload.html' => '上传头像',
  'view.html' => '用户详细信息',
);
?>