DROP TABLE IF EXISTS `phpcms_yp_apply`;
DROP TABLE IF EXISTS `phpcms_yp_buy`;
DROP TABLE IF EXISTS `phpcms_yp_cert`;
DROP TABLE IF EXISTS `phpcms_yp_collect`;
DROP TABLE IF EXISTS `phpcms_yp_count`;
DROP TABLE IF EXISTS `phpcms_yp_guestbook`;
DROP TABLE IF EXISTS `phpcms_yp_job`;
DROP TABLE IF EXISTS `phpcms_yp_news`;
DROP TABLE IF EXISTS `phpcms_yp_product`;
DROP TABLE IF EXISTS `phpcms_yp_relation`;
DROP TABLE IF EXISTS `phpcms_yp_stats`;
DROP TABLE IF EXISTS `phpcms_yp_stock`;
DELETE FROM `phpcms_category` WHERE module = 'yp';
DELETE FROM `phpcms_menu` WHERE keyid = 'yp';
DELETE FROM `phpcms_model` WHERE modeltype = '9';
DELETE FROM `phpcms_model` WHERE modeltype = '2' AND tablename = 'company';
DELETE FROM `phpcms_block` WHERE pageid = 'ypindex';
DELETE FROM `phpcms_block` WHERE pageid = 'yphead';