<?php
$templatenames = array (
  'category.html' => '栏目首页',
  'category_list.html' => '栏目列表页',
  'content.html' => '文章页',
  'contribute.html' => '游客投稿页',
  'index.html' => '频道首页',
  'myitem.html' => '我的文章',
  'search.html' => '文章搜索',
  'special_index.html' => '专题首页',
  'special_list.html' => '专题列表页',
  'special_show.html' => '专题页',
  'tag_article_list.html' => '[标签]文章标题列表',
  'tag_article_list-cat.html' => '[标签]终极栏目文章标题列表',
  'tag_article_related.html' => '[标签]相关文章列表',
  'tag_article_slide.html' => '[标签]幻灯片(flash)',
  'tag_article_slide-js.html' => '[标签]幻灯片(js)',
  'tag_article_thumb.html' => '[标签]图片文章列表',
  'type.html' => '分类首页',
  'type_list.html' => '分类列表页',
  'tag_article_thumb-sp6sypd.html' => 'sp6首页频道模板',
  'tag_article_list-sp6liebiao.html' => 'sp6文章标题列表',
  'tag_article_thumb-twlb.html' => '[标签]i图片文章列表',
  'tag_article_thumb-atlists.html' => '[标签]i栏目列表页文章列表',
  'tag_article_list-lmlsty.html' => '[标签]i栏目页_列表模板',
  'tag_article_list-soctlt.html' => '[标签]i专题内容列表',
);
?>