<?php
$tags_config = array (
  '专题幻灯片' => 
  array (
    'func' => 'phpcms_special_slide',
    'introduce' => '',
    'keyid' => '1',
    'specialnum' => '5',
    'specialnamelen' => '24',
    'iselite' => '0',
    'datenum' => '30',
    'imgwidth' => '250',
    'imgheight' => '220',
    'timeout' => '5000',
    'effectid' => '-1',
    'templateid' => '0',
    'edittime' => '2007-02-08 03:48:33',
    'editor' => 'phpcms',
    'longtag' => 'phpcms_special_slide(0,1,5,24,0,30,250,220,5000,-1)',
  ),
  '类别导航' => 
  array (
    'func' => 'phpcms_type',
    'introduce' => '',
    'keyid' => '$keyid',
    'templateid' => '0',
    'edittime' => '2007-01-14 11:42:30',
    'editor' => 'phpcms',
    'longtag' => 'phpcms_type(0,$keyid)',
  ),
  '文章专题列表' => 
  array (
    'func' => 'phpcms_special_list',
    'introduce' => '',
    'keyid' => '$channelid',
    'page' => '$page',
    'specialnum' => '10',
    'specialnamelen' => '50',
    'descriptionlen' => '200',
    'iselite' => '0',
    'datenum' => '0',
    'showtype' => '3',
    'imgwidth' => '150',
    'imgheight' => '150',
    'cols' => '1',
    'templateid' => '0',
    'edittime' => '2007-01-15 05:18:22',
    'editor' => 'phpcms',
    'longtag' => 'phpcms_special_list(0,$channelid,$page,10,50,200,0,0,3,150,150,1)',
  ),
  '文章推荐专题' => 
  array (
    'func' => 'phpcms_special_list',
    'introduce' => '',
    'keyid' => '$channelid',
    'page' => '0',
    'specialnum' => '10',
    'specialnamelen' => '50',
    'descriptionlen' => '100',
    'iselite' => '1',
    'datenum' => '0',
    'showtype' => '4',
    'imgwidth' => '100',
    'imgheight' => '100',
    'cols' => '1',
    'templateid' => '0',
    'edittime' => '2007-02-08 03:52:26',
    'editor' => 'phpcms',
    'longtag' => 'phpcms_special_list(0,$channelid,0,10,50,100,1,0,4,100,100,1)',
  ),
  '下载专题列表' => 
  array (
    'func' => 'phpcms_special_list',
    'introduce' => '',
    'keyid' => '$channelid',
    'page' => '$page',
    'specialnum' => '10',
    'specialnamelen' => '50',
    'descriptionlen' => '200',
    'iselite' => '0',
    'datenum' => '0',
    'showtype' => '3',
    'imgwidth' => '150',
    'imgheight' => '150',
    'cols' => '1',
    'templateid' => '0',
    'edittime' => '2007-01-15 05:16:23',
    'editor' => 'phpcms',
    'longtag' => 'phpcms_special_list(0,$channelid,$page,10,50,200,0,0,3,150,150,1)',
  ),
  '下载推荐专题' => 
  array (
    'func' => 'phpcms_special_list',
    'introduce' => '',
    'keyid' => '$channelid',
    'page' => '0',
    'specialnum' => '10',
    'specialnamelen' => '50',
    'descriptionlen' => '200',
    'iselite' => '1',
    'datenum' => '0',
    'showtype' => '4',
    'imgwidth' => '100',
    'imgheight' => '100',
    'cols' => '1',
    'templateid' => '0',
    'edittime' => '2007-01-15 05:17:51',
    'editor' => 'phpcms',
    'longtag' => 'phpcms_special_list(0,$channelid,0,10,50,200,1,0,4,100,100,1)',
  ),
  '图片专题列表' => 
  array (
    'func' => 'phpcms_special_list',
    'introduce' => '',
    'keyid' => '$channelid',
    'page' => '$page',
    'specialnum' => '10',
    'specialnamelen' => '50',
    'descriptionlen' => '200',
    'iselite' => '0',
    'datenum' => '0',
    'showtype' => '3',
    'imgwidth' => '150',
    'imgheight' => '150',
    'cols' => '1',
    'templateid' => '0',
    'edittime' => '2007-01-15 05:16:53',
    'editor' => 'phpcms',
    'longtag' => 'phpcms_special_list(0,$channelid,$page,10,50,200,0,0,3,150,150,1)',
  ),
  '图片推荐专题' => 
  array (
    'func' => 'phpcms_special_list',
    'introduce' => '',
    'keyid' => '$channelid',
    'page' => '0',
    'specialnum' => '10',
    'specialnamelen' => '50',
    'descriptionlen' => '200',
    'iselite' => '1',
    'datenum' => '0',
    'showtype' => '4',
    'imgwidth' => '100',
    'imgheight' => '100',
    'cols' => '1',
    'templateid' => '0',
    'edittime' => '2007-01-15 05:17:36',
    'editor' => 'phpcms',
    'longtag' => 'phpcms_special_list(0,$channelid,0,10,50,200,1,0,4,100,100,1)',
  ),
  '信息专题列表' => 
  array (
    'func' => 'phpcms_special_list',
    'introduce' => '',
    'keyid' => '$channelid',
    'page' => '$page',
    'specialnum' => '10',
    'specialnamelen' => '50',
    'descriptionlen' => '200',
    'iselite' => '0',
    'datenum' => '0',
    'showtype' => '3',
    'imgwidth' => '150',
    'imgheight' => '150',
    'cols' => '1',
    'templateid' => '0',
    'edittime' => '2007-01-15 05:18:52',
    'editor' => 'phpcms',
    'longtag' => 'phpcms_special_list(0,$channelid,$page,10,50,200,0,0,3,150,150,1)',
  ),
  '信息推荐专题' => 
  array (
    'func' => 'phpcms_special_list',
    'introduce' => '',
    'keyid' => '$channelid',
    'page' => '0',
    'specialnum' => '10',
    'specialnamelen' => '50',
    'descriptionlen' => '200',
    'iselite' => '1',
    'datenum' => '0',
    'showtype' => '4',
    'imgwidth' => '100',
    'imgheight' => '100',
    'cols' => '1',
    'templateid' => '0',
    'edittime' => '2007-01-15 05:19:19',
    'editor' => 'phpcms',
    'longtag' => 'phpcms_special_list(0,$channelid,0,10,50,200,1,0,4,100,100,1)',
  ),
  '文章频道首页专题列表' => 
  array (
    'func' => 'phpcms_special_list',
    'introduce' => '',
    'keyid' => '$channelid',
    'page' => '0',
    'specialnum' => '1',
    'specialnamelen' => '32',
    'descriptionlen' => '80',
    'iselite' => '0',
    'datenum' => '0',
    'showtype' => '4',
    'imgwidth' => '80',
    'imgheight' => '100',
    'cols' => '1',
    'templateid' => '0',
    'edittime' => '2007-02-09 10:01:09',
    'editor' => 'phpcms',
    'longtag' => 'phpcms_special_list(0,$channelid,0,1,32,80,0,0,4,80,100,1)',
  ),
  '频道一级栏目' => 
  array (
    'func' => 'phpcms_cat',
    'introduce' => '',
    'keyid' => '$channelid',
    'catid' => '0',
    'child' => '1',
    'open' => '1',
    'showtype' => '2',
    'templateid' => 'tag_cat-1',
    'edittime' => '2007-01-15 06:34:39',
    'editor' => 'phpcms',
    'longtag' => 'phpcms_cat(\'tag_cat-1\',$channelid,0,1,2,1)',
  ),
  '频道子栏目列表' => 
  array (
    'func' => 'phpcms_cat',
    'introduce' => '',
    'keyid' => '$channelid',
    'catid' => '$catid',
    'child' => '1',
    'open' => '1',
    'showtype' => '2',
    'templateid' => 'tag_cat-sub',
    'edittime' => '2007-01-15 06:34:55',
    'editor' => 'phpcms',
    'longtag' => 'phpcms_cat(\'tag_cat-sub\',$channelid,$catid,1,2,1)',
  ),
  '下载频道首页专题' => 
  array (
    'func' => 'phpcms_special_list',
    'introduce' => '',
    'keyid' => '$channelid',
    'page' => '0',
    'specialnum' => '1',
    'specialnamelen' => '30',
    'descriptionlen' => '200',
    'iselite' => '0',
    'datenum' => '0',
    'showtype' => '4',
    'imgwidth' => '60',
    'imgheight' => '60',
    'cols' => '1',
    'templateid' => '0',
    'edittime' => '2007-01-17 03:57:21',
    'editor' => 'phpcms',
    'longtag' => 'phpcms_special_list(0,$channelid,0,1,30,200,0,0,4,60,60,1)',
  ),
  '图片频道首页专题' => 
  array (
    'func' => 'phpcms_special_list',
    'introduce' => '',
    'keyid' => '$channelid',
    'page' => '0',
    'specialnum' => '1',
    'specialnamelen' => '30',
    'descriptionlen' => '200',
    'iselite' => '0',
    'datenum' => '0',
    'showtype' => '4',
    'imgwidth' => '60',
    'imgheight' => '60',
    'cols' => '1',
    'templateid' => '0',
    'edittime' => '2007-01-17 03:57:29',
    'editor' => 'phpcms',
    'longtag' => 'phpcms_special_list(0,$channelid,0,1,30,200,0,0,4,60,60,1)',
  ),
  '模块一级栏目' => 
  array (
    'func' => 'phpcms_cat',
    'introduce' => '',
    'keyid' => '$mod',
    'catid' => '0',
    'child' => '1',
    'open' => '1',
    'showtype' => '2',
    'templateid' => 'tag_cat-1',
    'edittime' => '2007-01-15 06:34:47',
    'editor' => 'phpcms',
    'longtag' => 'phpcms_cat(\'tag_cat-1\',$mod,0,1,2,1)',
  ),
  '模块子栏目列表' => 
  array (
    'func' => 'phpcms_cat',
    'introduce' => '',
    'keyid' => '$mod',
    'catid' => '$catid',
    'child' => '1',
    'open' => '1',
    'showtype' => '2',
    'templateid' => 'tag_cat-sub',
    'edittime' => '2007-01-15 06:36:54',
    'editor' => 'phpcms',
    'longtag' => 'phpcms_cat(\'tag_cat-sub\',$mod,$catid,1,2,1)',
  ),
  '网站首页推荐专题' => 
  array (
    'func' => 'phpcms_special_list',
    'introduce' => '',
    'keyid' => '1',
    'page' => '0',
    'specialnum' => '2',
    'specialnamelen' => '34',
    'descriptionlen' => '100',
    'iselite' => '1',
    'datenum' => '30',
    'showtype' => '4',
    'imgwidth' => '80',
    'imgheight' => '100',
    'cols' => '1',
    'templateid' => '0',
    'edittime' => '2007-02-09 09:58:46',
    'editor' => 'phpcms',
    'longtag' => 'phpcms_special_list(0,1,0,2,34,100,1,30,4,80,100,1)',
  ),
  '首页幻灯片' => 
  array (
    'type' => '首页幻灯片',
    'func' => 'phpcms_freelink',
    'keyid' => 'phpcms',
    'edittime' => '2007-03-24 03:14:42',
    'editor' => 'phpcms',
    'longtag' => 'phpcms_freelink(\'首页幻灯片\')',
  ),
  '首页推荐信息' => 
  array (
    'type' => '首页推荐信息',
    'func' => 'phpcms_freelink',
    'keyid' => 'phpcms',
    'edittime' => '2007-03-24 03:14:37',
    'editor' => 'phpcms',
    'longtag' => 'phpcms_freelink(\'首页推荐信息\')',
  ),
);
?>