<?php
$templatenames = array (
  'admin_mymenu.html' => '后台常用操作模板',
  'admin_quick_add.html' => '后台快捷操作-添加',
  'admin_quick_cache.html' => '后台快捷操作-缓存',
  'admin_quick_create.html' => '后台快捷操作-html',
  'admin_quick_infolist.html' => '后台快捷操作-列表',
  'admin_quick_make.html' => '后台快捷操作-创建',
  'admin_top.html' => '后台顶部导航',
  'area.html' => '地区',
  'city.html' => '城市',
  'footer.html' => '页脚模板',
  'freelink_list.html' => '自由调用文字显示模板',
  'freelink_slide.html' => '自由调用幻灯片显示模板',
  'freelink_thumb.html' => '自由调用图片显示模板',
  'header.html' => '页头',
  'index.html' => '首页模板',
  'province.html' => '省份',
  'search.html' => '搜索',
  'showmessage.html' => '提示信息',
  'tag_cat.html' => '栏目标签模板',
  'tag_cat-1.html' => '一级栏目标签模板',
  'tag_cat-sub.html' => '子栏目标签模板',
  'tag_special_list.html' => '专题列表标签模板',
  'tag_special_slide.html' => '专题幻灯片标签模板（Flash）',
  'tag_special_slide-js.html' => '专题幻灯片标签模板（JS）',
  'tag_type.html' => '分类标签模板',
  'uppic.html' => '上传图片',
);
?>