<?php
$templatenames = array (
  'admin_mymenu.html' => '后台常用操作',
  'admin_quick_add.html' => '后台快捷操作-添加',
  'admin_quick_cache.html' => '后台快捷操作-缓存',
  'admin_quick_create.html' => '后台快捷操作-html',
  'admin_quick_infolist.html' => '后台快捷操作-列表',
  'admin_quick_make.html' => '后台快捷操作-创建',
  'admin_top.html' => '后台顶部导航',
  'area.html' => '地区',
  'city.html' => '城市',
  'footer.html' => '页脚',
  'freelink_list.html' => '自由调用文字显示',
  'freelink_slide.html' => '自由调用幻灯片显示',
  'freelink_thumb.html' => '自由调用图片显示',
  'header.html' => '页头',
  'index.html' => '网站首页',
  'province.html' => '省份',
  'search.html' => '搜索框',
  'showmessage.html' => '提示信息',
  'tag_cat.html' => '[标签]栏目',
  'tag_cat-1.html' => '[标签]一级栏目',
  'tag_cat-sub.html' => '[标签]子栏目',
  'tag_phpcms_tm.html' => '在线咨询',
  'tag_special_list.html' => '[标签]专题列表',
  'tag_special_slide.html' => '[标签]专题幻灯片(fash)',
  'tag_special_slide-js.html' => '[标签]专题幻灯片(js)',
  'tag_type.html' => '[标签]分类',
  'upload.html' => '文件上传',
);
?>