INSERT INTO `phpcms_module` (`name`, `module`, `moduledir`, `moduledomain`, `iscore`, `iscopy`, `isshare`, `version`, `author`, `site`, `email`, `introduce`, `license`, `faq`, `setting`, `disabled`, `publishdate`, `installdate`, `updatedate`) VALUES
('企业黄页', 'yp', 'yp', '', 0, 0, 0, '1.0.0', 'phpcms', 'http://www.phpcms.cn', 'phpcms@163.com', '企业黄页', '', '', '', 0, '0000-00-00', '0000-00-00', '0000-00-00');

INSERT INTO `phpcms_menu` ( `position`, `name`, `title`, `url`, `target`, `style`, `listorder`, `arrgroupid`, `arrgrade`, `username`) VALUES 
('member_menu', '我的简历', '', 'yp/myitem.php', '_self', '', 100, '', '', '');

INSERT INTO `phpcms_channel` (`module`, `channelname`, `style`, `channelpic`, `introduce`, `seo_title`, `seo_keywords`, `seo_description`, `listorder`, `islink`, `channeldir`, `channeldomain`, `disabled`, `templateid`, `skinid`, `items`, `comments`, `categorys`, `specials`, `hits`, `enablepurview`, `arrgroupid_browse`, `purview_message`, `point_message`, `enablecontribute`, `enablecheck`, `emailofreject`, `emailofpassed`, `enableupload`, `uploaddir`, `maxfilesize`, `uploadfiletype`, `linkurl`, `setting`, `ishtml`, `cat_html_urlruleid`, `item_html_urlruleid`, `special_html_urlruleid`, `cat_php_urlruleid`, `item_php_urlruleid`, `special_php_urlruleid`) VALUES 
('yp', '企业黄页', '', '', '', '', '', '', 7, 1, '', '', 0, '0', '0', 0, 0, 0, 0, 0, 0, '', '<div align=''center'' style=''color:red''>对不起，您没有阅读权限！</div>', '<p align=''center''><span style=''background:#E3E3E3''><a href=''{$readurl}'' class=''read''>阅读本文需要消耗<font color=''red''>{$readpoint}</font>点，您确认查看吗？</a></span></p><br/>', 1, 1, '', '', 1, 'uploadfile', 1024000, 'gif|jpg', 'yp/', '', 1, 0, 0, 0, 0, 0, 0);


DROP TABLE IF EXISTS `phpcms_member_company`;
CREATE TABLE IF NOT EXISTS `phpcms_member_company` (
  `companyid` int(10) unsigned NOT NULL auto_increment,
  `companyname` varchar(100) NOT NULL,
  `username` varchar(20) NOT NULL,
  `listorder` int(10) unsigned NOT NULL default '0',
  `pattern` varchar(255) NOT NULL,
  `tradeid` int(6) unsigned NOT NULL default '0',
  `typeid` varchar(255) NOT NULL,
  `product` mediumtext NOT NULL,
  `regtime` int(10) unsigned NOT NULL default '0',
  `areaid` int(10) unsigned NOT NULL default '0',
  `employnum` varchar(50) NOT NULL,
  `turnover` varchar(50) NOT NULL,
  `status` tinyint(1) NOT NULL default '0',
  `sitedomain` varchar(255) default NULL,
  `logo` varchar(255) NOT NULL,
  `banner` varchar(255) NOT NULL,
  `background` varchar(255) NOT NULL,
  `linkman` varchar(50) NOT NULL,
  `telephone` varchar(50) NOT NULL,
  `fax` varchar(50) NOT NULL,
  `postid` varchar(6) NOT NULL,
  `email` varchar(255) NOT NULL,
  `address` varchar(255) NOT NULL,
  `homepage` varchar(255) NOT NULL,
  `introduce` mediumtext NOT NULL,
  `elite` tinyint(1) unsigned NOT NULL default '0',
  `templateid` varchar(100) NOT NULL,
  `menu` text NOT NULL,
  `addtime` int(10) unsigned NOT NULL default '0',
  `checker` varchar(20) NOT NULL,
  `checktime` int(10) unsigned NOT NULL default '0',
  `editor` varchar(20) NOT NULL,
  `edittime` int(10) unsigned NOT NULL default '0',
  `linkurl` varchar(255) NOT NULL,
  `hits` int(10) unsigned NOT NULL default '0',
  `map` varchar(255) NOT NULL,
  `vip` int(10) unsigned NOT NULL default '0',
  `my_yplink` varchar(255) NOT NULL default '',
  PRIMARY KEY  (`companyid`),
  UNIQUE KEY `username` (`username`),
  KEY `sitedomain` (`sitedomain`),
  KEY `hits` (`hits`,`status`,`companyid`),
  KEY `typeid` (`typeid`,`status`,`listorder`,`companyid`)
) TYPE=MyISAM;

DROP TABLE IF EXISTS `phpcms_yp_apply`;
CREATE TABLE IF NOT EXISTS `phpcms_yp_apply` (
  `applyid` int(11) unsigned NOT NULL auto_increment,
  `station` varchar(200) NOT NULL,
  `experience` varchar(20) NOT NULL,
  `worktype` varchar(10) NOT NULL,
  `pay` int(8) unsigned NOT NULL,
  `linkman` varchar(20) NOT NULL,
  `introduce` mediumtext NOT NULL,
  `story` mediumtext NOT NULL,
  `status` tinyint(1) NOT NULL default '0',
  `linkurl` varchar(255) NOT NULL,
  `username` varchar(20) NOT NULL,
  `hits` int(10) unsigned NOT NULL default '0',
  `listorder` int(10) unsigned NOT NULL,
  `addtime` int(10) unsigned NOT NULL default '0',
  `editor` varchar(20) NOT NULL,
  `edittime` int(10) unsigned NOT NULL default '0',
  `graduatetime` varchar(50) NOT NULL,
  `school` varchar(255) NOT NULL,
  `specialty` varchar(255) NOT NULL,
  `area` varchar(255) NOT NULL,
  `period` smallint(3) unsigned NOT NULL,
  PRIMARY KEY  (`applyid`),
  UNIQUE KEY `username` (`username`),
  KEY `station` (`station`,`status`,`listorder`,`applyid`)
) TYPE=MyISAM;

DROP TABLE IF EXISTS `phpcms_yp_article`;
CREATE TABLE IF NOT EXISTS `phpcms_yp_article` (
  `articleid` int(10) unsigned NOT NULL auto_increment,
  `catid` smallint(5) unsigned NOT NULL default '0',
  `companyid` int(10) unsigned NOT NULL default '0',
  `title` varchar(100) NOT NULL default '',
  `style` varchar(50) NOT NULL default '',
  `content` mediumtext NOT NULL,
  `keywords` varchar(100) NOT NULL default '',
  `hits` int(10) unsigned NOT NULL default '0',
  `comments` int(10) unsigned NOT NULL default '0',
  `thumb` varchar(255) NOT NULL default '',
  `username` varchar(20) NOT NULL default '',
  `addtime` int(10) unsigned NOT NULL default '0',
  `editor` varchar(25) NOT NULL default '',
  `edittime` int(10) unsigned NOT NULL default '0',
  `checker` varchar(25) NOT NULL default '',
  `checktime` int(10) unsigned NOT NULL default '0',
  `arrposid` varchar(50) NOT NULL default '',
  `status` tinyint(1) NOT NULL default '0',
  `listorder` smallint(4) unsigned NOT NULL default '0',
  `islink` tinyint(1) unsigned NOT NULL default '0',
  `linkurl` varchar(255) NOT NULL default '',
  PRIMARY KEY  (`articleid`),
  KEY `catid` (`catid`,`status`,`listorder`,`articleid`),
  KEY `username` (`username`(10)),
  KEY `hits` (`status`,`hits`,`articleid`),
  KEY `companyid` (`companyid`,`articleid`,`status`,`listorder`),
  FULLTEXT KEY `keywords` (`keywords`)
) TYPE=MyISAM;

DROP TABLE IF EXISTS `phpcms_yp_guestbook`;
CREATE TABLE `phpcms_yp_guestbook` (
  `gid` int(11) unsigned NOT NULL auto_increment,
  `companyid` int(10) unsigned NOT NULL default '0',
  `itemid` int(11) unsigned NOT NULL default '0',
  `username` varchar(20) NOT NULL,
  `fax` varchar(100) NOT NULL,
  `telephone` varchar(100) NOT NULL,
  `qq` int(10) unsigned NOT NULL default '0',
  `unit` varchar(255) NOT NULL,
  `msn` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `content` mediumtext NOT NULL,
  `status` tinyint(1) unsigned NOT NULL default '0',
  `label` varchar(255) NOT NULL,
  `addtime` int(10) unsigned NOT NULL default '0',
  PRIMARY KEY  (`gid`),
  KEY `companyid` (`companyid`,`status`,`gid`)
) TYPE=MyISAM;

DROP TABLE IF EXISTS `phpcms_yp_job`;
CREATE TABLE IF NOT EXISTS `phpcms_yp_job` (
  `jobid` int(11) unsigned NOT NULL auto_increment,
  `title` varchar(255) NOT NULL,
  `style` varchar(100) NOT NULL,
  `station` varchar(200) NOT NULL,
  `employ` int(6) unsigned NOT NULL,
  `experience` varchar(20) NOT NULL,
  `worktype` varchar(10) NOT NULL,
  `sex` tinyint(1) unsigned NOT NULL,
  `degree` varchar(10) NOT NULL,
  `pay` int(8) unsigned NOT NULL,
  `areaid` int(10) unsigned NOT NULL default '0',
  `unit` varchar(255) NOT NULL,
  `linkman` varchar(20) NOT NULL,
  `email` varchar(255) NOT NULL,
  `phone` varchar(100) NOT NULL,
  `address` varchar(255) NOT NULL,
  `introduce` mediumtext NOT NULL,
  `period` int(4) unsigned NOT NULL,
  `status` tinyint(1) NOT NULL default '0',
  `linkurl` varchar(255) NOT NULL,
  `companyid` int(11) unsigned NOT NULL default '0',
  `username` varchar(20) NOT NULL,
  `hits` int(10) unsigned NOT NULL default '0',
  `listorder` int(10) unsigned NOT NULL,
  `addtime` int(10) unsigned NOT NULL default '0',
  `checker` varchar(20) NOT NULL,
  `checktime` int(10) unsigned NOT NULL default '0',
  `editor` varchar(20) NOT NULL,
  `edittime` int(10) unsigned NOT NULL default '0',
  PRIMARY KEY  (`jobid`),
  KEY `label` (`status`,`jobid`),
  KEY `listorder` (`listorder`,`status`,`jobid`),
  KEY `hits` (`hits`,`status`,`jobid`),
  KEY `username` (`username`(10)),
  KEY `companyid` (`companyid`,`status`,`listorder`,`jobid`)
) TYPE=MyISAM;

DROP TABLE IF EXISTS `phpcms_yp_product`;
CREATE TABLE IF NOT EXISTS `phpcms_yp_product` (
  `productid` int(11) unsigned NOT NULL auto_increment,
  `title` varchar(80) NOT NULL,
  `catid` int(5) unsigned NOT NULL default '0',
  `companyid` int(10) unsigned NOT NULL default '0',
  `keywords` varchar(255) NOT NULL,
  `style` varchar(80) NOT NULL,
  `model` varchar(255) NOT NULL,
  `thumb` varchar(255) NOT NULL,
  `price` decimal(10,2) NOT NULL default '0.00',
  `quantifier` varchar(20) NOT NULL,
  `introduce` mediumtext NOT NULL,
  `unit` varchar(255) NOT NULL,
  `linkman` varchar(20) NOT NULL,
  `email` varchar(255) NOT NULL,
  `phone` varchar(100) NOT NULL,
  `address` varchar(255) NOT NULL,
  `addtime` int(10) unsigned NOT NULL default '0',
  `username` varchar(20) NOT NULL,
  `edittime` int(10) unsigned NOT NULL default '0',
  `editor` varchar(20) NOT NULL,
  `checker` varchar(20) NOT NULL,
  `checktime` int(10) unsigned NOT NULL default '0',
  `linkurl` varchar(255) NOT NULL,
  `hits` int(10) unsigned NOT NULL default '0',
  `listorder` int(5) unsigned NOT NULL default '0',
  `status` tinyint(1) NOT NULL default '0',
  PRIMARY KEY  (`productid`),
  KEY `listorder` (`listorder`,`productid`,`status`),
  KEY `catid` (`catid`,`listorder`,`status`),
  KEY `hits` (`hits`,`productid`,`status`),
  KEY `username` (`username`(10)),
  KEY `companyid` (`companyid`,`productid`,`listorder`,`status`),
  FULLTEXT KEY `keywords` (`keywords`)
) TYPE=MyISAM;

DROP TABLE IF EXISTS `phpcms_yp_sales`;
CREATE TABLE IF NOT EXISTS `phpcms_yp_sales` (
  `productid` int(11) unsigned NOT NULL auto_increment,
  `title` varchar(80) NOT NULL,
  `catid` int(5) unsigned NOT NULL default '0',
  `companyid` int(10) unsigned NOT NULL default '0',
  `keywords` varchar(255) NOT NULL,
  `style` varchar(80) NOT NULL,
  `thumb` varchar(255) NOT NULL,
  `price` decimal(10,2) NOT NULL default '0.00',
  `quantifier` varchar(20) NOT NULL,
  `formerprice` decimal(10,2) NOT NULL default '0.00',
  `period` int(10) unsigned NOT NULL default '0',
  `introduce` mediumtext NOT NULL,
  `state` tinytext NOT NULL,
  `unit` varchar(255) NOT NULL,
  `linkman` varchar(20) NOT NULL,
  `email` varchar(255) NOT NULL,
  `phone` varchar(100) NOT NULL,
  `address` varchar(255) NOT NULL,
  `addtime` int(10) unsigned NOT NULL default '0',
  `username` varchar(20) NOT NULL,
  `edittime` int(10) unsigned NOT NULL default '0',
  `editor` varchar(20) NOT NULL,
  `checker` varchar(20) NOT NULL,
  `checktime` int(10) unsigned NOT NULL default '0',
  `linkurl` varchar(255) NOT NULL,
  `hits` int(10) unsigned NOT NULL default '0',
  `listorder` int(5) unsigned NOT NULL default '0',
  `status` tinyint(1) NOT NULL default '0',
  PRIMARY KEY  (`productid`),
  KEY `catid` (`catid`,`listorder`,`status`),
  KEY `username` (`username`(10)),
  KEY `companyid` (`companyid`,`status`,`listorder`,`productid`),
  KEY `hits` (`hits`,`status`,`productid`),
  FULLTEXT KEY `keywords` (`keywords`)
) TYPE=MyISAM;

DROP TABLE IF EXISTS `phpcms_yp_buy`;
CREATE TABLE IF NOT EXISTS `phpcms_yp_buy` (
  `productid` int(11) unsigned NOT NULL auto_increment,
  `title` varchar(80) NOT NULL,
  `catid` int(5) unsigned NOT NULL default '0',
  `companyid` int(10) unsigned NOT NULL default '0',
  `keywords` varchar(255) NOT NULL,
  `style` varchar(80) NOT NULL,
  `period` int(10) unsigned NOT NULL default '0',
  `introduce` mediumtext NOT NULL,
  `unit` varchar(255) NOT NULL,
  `linkman` varchar(20) NOT NULL,
  `email` varchar(255) NOT NULL,
  `phone` varchar(100) NOT NULL,
  `address` varchar(255) NOT NULL,
  `addtime` int(10) unsigned NOT NULL default '0',
  `username` varchar(20) NOT NULL,
  `edittime` int(10) unsigned NOT NULL default '0',
  `editor` varchar(20) NOT NULL,
  `checker` varchar(20) NOT NULL,
  `checktime` int(10) unsigned NOT NULL default '0',
  `linkurl` varchar(255) NOT NULL,
  `hits` int(10) unsigned NOT NULL default '0',
  `listorder` int(5) unsigned NOT NULL default '0',
  `status` tinyint(1) NOT NULL default '0',
  `my_selecttype` varchar(50) NOT NULL default '',
  `my_buyprice` varchar(50) NOT NULL default '',
  PRIMARY KEY  (`productid`),
  KEY `hits` (`hits`,`productid`,`status`),
  KEY `username` (`username`(10)),
  KEY `catid` (`catid`,`status`,`listorder`,`productid`),
  KEY `companyid` (`companyid`,`status`,`listorder`,`productid`),
  FULLTEXT KEY `keywords` (`keywords`)
) TYPE=MyISAM;

DROP TABLE IF EXISTS `phpcms_yp_trade`;
CREATE TABLE IF NOT EXISTS `phpcms_yp_trade` (
  `tradeid` smallint(6) unsigned NOT NULL auto_increment,
  `script` varchar(20) NOT NULL,
  `tradename` varchar(50) NOT NULL default '',
  `domain` varchar(50) NOT NULL default '',
  `style` varchar(50) NOT NULL default '',
  `parentid` smallint(6) unsigned NOT NULL default '0',
  `arrparentid` varchar(255) NOT NULL default '',
  `child` tinyint(1) NOT NULL default '0',
  `arrchildid` mediumtext NOT NULL,
  `listorder` smallint(6) unsigned NOT NULL default '0',
  `urlruleid` tinyint(1) unsigned NOT NULL default '0',
  `linkurl` varchar(255) NOT NULL default '',
  `setting` mediumtext NOT NULL,
  `hits` int(11) unsigned NOT NULL default '0',
  `disabled` tinyint(1) NOT NULL default '0',
  PRIMARY KEY  (`tradeid`),
  KEY `listorder` (`listorder`),
 KEY `script` (`script`,`disabled`,`listorder`)
) TYPE=MyISAM;

DROP TABLE IF EXISTS `phpcms_yp_stock`;
CREATE TABLE IF NOT EXISTS `phpcms_yp_stock` (
  `stockid` int(10) unsigned NOT NULL auto_increment,
  `jobid` int(10) unsigned NOT NULL,
  `label` tinyint(1) NOT NULL,
  `status` tinyint(1) unsigned NOT NULL,
  `username` varchar(20) NOT NULL,
  `addtime` int(10) unsigned NOT NULL,
  PRIMARY KEY  (`stockid`),
  KEY `jobid` (`jobid`,`status`,`label`)
) TYPE=MyISAM;

CREATE TABLE IF NOT EXISTS `phpcms_area` (
  `areaid` smallint(6) unsigned NOT NULL auto_increment,
  `keyid` varchar(20) NOT NULL,
  `areaname` varchar(50) NOT NULL default '',
  `domain` varchar(50) NOT NULL default '',
  `style` varchar(50) NOT NULL default '',
  `parentid` smallint(6) unsigned NOT NULL default '0',
  `arrparentid` varchar(255) NOT NULL default '',
  `child` tinyint(1) NOT NULL default '0',
  `arrchildid` mediumtext NOT NULL,
  `listorder` smallint(6) unsigned NOT NULL default '0',
  `urlruleid` tinyint(1) unsigned NOT NULL default '0',
  `linkurl` varchar(255) NOT NULL default '',
  `setting` mediumtext NOT NULL,
  `hits` int(11) unsigned NOT NULL default '0',
  `disabled` tinyint(1) NOT NULL default '0',
  PRIMARY KEY  (`areaid`),
  KEY `listorder` (`listorder`),
  KEY `keyid` (`keyid`,`disabled`,`listorder`)
) TYPE=MyISAM;

DROP TABLE IF EXISTS `phpcms_yp_order`;
CREATE TABLE IF NOT EXISTS `phpcms_yp_order` (
  `orderid` int(11) unsigned NOT NULL auto_increment,
  `companyid` int(10) unsigned NOT NULL default '0',
  `title` varchar(255) NOT NULL,
  `number` int(10) unsigned NOT NULL default '0',
  `order_no` varchar(30) NOT NULL,
  `content` text NOT NULL,
  `linkman` varchar(20) NOT NULL,
  `username` varchar(20) NOT NULL,
  `telephone` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `qq` int(10) unsigned NOT NULL default '0',
  `msn` varchar(255) NOT NULL,
  `fax` varchar(255) NOT NULL,
  `unit` varchar(255) NOT NULL,
  `status` tinyint(1) unsigned NOT NULL default '0',
  `itemid` int(11) unsigned NOT NULL default '0',
  `label` varchar(20) NOT NULL,
  `addtime` int(10) unsigned NOT NULL default '0',
  PRIMARY KEY  (`orderid`),
  UNIQUE KEY `order_no` (`order_no`),
  KEY `orderid` (`orderid`,`status`,`itemid`,`label`)
)TYPE=MyISAM;
INSERT INTO `phpcms_field` (`tablename`, `name`, `size`, `title`, `note`, `type`, `defaultvalue`, `options`, `formtype`, `inputtool`, `inputlimit`, `listorder`, `enablehtml`, `enablelist`, `enablesearch`) VALUES('phpcms_yp_buy', 'my_selecttype', 250, '求购-出售-转让-其他', '', 'varchar', '', '求购|<b>求购</b>\r\n出售|出售\r\n转让|转让\r\n其他|其他', 'select', '', 'notnull', 0, 1, 1, 0);
INSERT INTO `phpcms_field` (`tablename`, `name`, `size`, `title`, `note`, `type`, `defaultvalue`, `options`, `formtype`, `inputtool`, `inputlimit`, `listorder`, `enablehtml`, `enablelist`, `enablesearch`) VALUES('phpcms_yp_buy', 'my_buyprice', 250, '价格', '', 'varchar', '', '选项一|选项值一\r\n选项二|选项值二\r\n选项三|选项值三', 'text', '', 'notnull', 0, 1, 1, 0);
INSERT INTO `phpcms_field` (`tablename`, `name`, `size`, `title`, `note`, `type`, `defaultvalue`, `options`, `formtype`, `inputtool`, `inputlimit`, `listorder`, `enablehtml`, `enablelist`, `enablesearch`) VALUES('phpcms_member_company', 'my_yplink', 250, '友情链接图片：', '黄页企业友情链接', 'varchar', '', '选项一|选项值一\r\n选项二|选项值二\r\n选项三|选项值三', 'text', 'imageupload', '', 0, 1, 1, 0);