<?php
$templatenames = array (
  'category.html' => '栏目首页',
  'category_list.html' => '栏目列表页',
  'content.html' => '下载页',
  'contribute.html' => '游客投稿',
  'down.html' => '最终下载页',
  'index.html' => '频道首页',
  'myitem.html' => '我的下载',
  'search.html' => '搜索页',
  'special_index.html' => '专题首页',
  'special_list.html' => '专题列表页',
  'special_show.html' => '专题页',
  'tag_down_list.html' => '[标签]下载标题列表',
  'tag_down_list-cat.html' => '[标签]终极栏目标题列表',
  'tag_down_related.html' => '[标签]相关下载',
  'tag_down_slide.html' => '[标签]下载幻灯片(flash)',
  'tag_down_slide-js.html' => '[标签]下载幻灯片(js)',
  'tag_down_thumb.html' => '[标签]下载缩略图',
  'type.html' => '分类首页',
  'type_list.html' => '分类下载列表',
  'tag_down_list-sp6.html' => 'sp6下载标题列表',
  'tag_down_list-downph.html' => 'i下载排行列表',
  'tag_down_list-sp6wd.html' => '[标签]sp6下载列表',
  'tag_down_list-dowlt.html' => '[标签]i下载列表页_列表',
  'tag_down_list-downlt.html' => '[标签]i下载列表icon',
  'tag_down_slide-flashlb.html' => '[标签]iflash轮播',
);
?>