<?php
$tags_config = array (
  '商城首页链接' => 
  array (
    'func' => 'link_list',
    'introduce' => '',
    'linktype' => '1',
    'typeid' => '0',
    'showhits' => '1',
    'linknum' => '20',
    'cols' => '2',
    'templateid' => '0',
    'edittime' => '2007-02-10 10:53:08',
    'editor' => 'phpcms',
    'longtag' => 'link_list(0,0,1,20,2,1)',
  ),
  '网站首页文字链接' => 
  array (
    'func' => 'link_list',
    'introduce' => '',
    'linktype' => '0',
    'typeid' => '0',
    'showhits' => '1',
    'linknum' => '20',
    'cols' => '2',
    'templateid' => '0',
    'edittime' => '2007-01-15 03:30:02',
    'editor' => 'phpcms',
    'longtag' => 'link_list(0,0,0,20,2,1)',
  ),
  '网站首页图片链接' => 
  array (
    'func' => 'link_list',
    'introduce' => '',
    'linktype' => '1',
    'typeid' => '0',
    'showhits' => '1',
    'linknum' => '20',
    'cols' => '2',
    'templateid' => '0',
    'edittime' => '2007-01-15 03:40:29',
    'editor' => 'phpcms',
    'longtag' => 'link_list(0,0,1,20,2,1)',
  ),
  '文章频道首页logo链接' => 
  array (
    'func' => 'link_list',
    'introduce' => '',
    'linktype' => '1',
    'typeid' => '0',
    'showhits' => '1',
    'linknum' => '10',
    'cols' => '2',
    'templateid' => '0',
    'edittime' => '2007-02-10 10:57:31',
    'editor' => 'phpcms',
    'longtag' => 'link_list(0,0,1,10,2,1)',
  ),
  '文章频道首页文字链接' => 
  array (
    'func' => 'link_list',
    'introduce' => '',
    'linktype' => '0',
    'typeid' => '0',
    'showhits' => '1',
    'linknum' => '20',
    'cols' => '2',
    'templateid' => '0',
    'edittime' => '2007-02-10 10:56:00',
    'editor' => 'phpcms',
    'longtag' => 'link_list(0,0,0,20,2,1)',
  ),
  '下载频道首页logo链接' => 
  array (
    'func' => 'link_list',
    'introduce' => '',
    'linktype' => '1',
    'typeid' => '0',
    'showhits' => '1',
    'linknum' => '10',
    'cols' => '2',
    'templateid' => '0',
    'edittime' => '2007-02-10 10:57:10',
    'editor' => 'phpcms',
    'longtag' => 'link_list(0,0,1,10,2,1)',
  ),
  '下载频道首页文字链接' => 
  array (
    'func' => 'link_list',
    'introduce' => '',
    'linktype' => '0',
    'typeid' => '0',
    'showhits' => '1',
    'linknum' => '20',
    'cols' => '2',
    'templateid' => '0',
    'edittime' => '2007-02-10 10:55:41',
    'editor' => 'phpcms',
    'longtag' => 'link_list(0,0,0,20,2,1)',
  ),
  '图片频道首页logo链接' => 
  array (
    'func' => 'link_list',
    'introduce' => '',
    'linktype' => '1',
    'typeid' => '0',
    'showhits' => '1',
    'linknum' => '10',
    'cols' => '2',
    'templateid' => '0',
    'edittime' => '2007-02-10 10:57:24',
    'editor' => 'phpcms',
    'longtag' => 'link_list(0,0,1,10,2,1)',
  ),
  '图片频道首页文字链接' => 
  array (
    'func' => 'link_list',
    'introduce' => '',
    'linktype' => '0',
    'typeid' => '0',
    'showhits' => '1',
    'linknum' => '20',
    'cols' => '2',
    'templateid' => '0',
    'edittime' => '2007-02-10 10:55:19',
    'editor' => 'phpcms',
    'longtag' => 'link_list(0,0,0,20,2,1)',
  ),
);
?>