DROP TABLE IF EXISTS `phpcms_movie`;
CREATE TABLE `phpcms_movie` (
  `movieid` int(10) unsigned NOT NULL auto_increment,
  `catid` smallint(5) unsigned NOT NULL default '0',
  `specialid` smallint(5) unsigned NOT NULL default '0',
  `typeid` smallint(5) unsigned NOT NULL default '0',
  `letter` varchar(1) NOT NULL,
  `title` varchar(100) NOT NULL default '',
  `style` varchar(50) NOT NULL default '',
  `introduce` mediumtext NOT NULL,
  `keywords` varchar(100) NOT NULL default '',
  `onlineview` tinyint(1) unsigned NOT NULL,
  `allowdown` tinyint(1) unsigned NOT NULL,
  `serverid` smallint(5) unsigned NOT NULL default '0',
  `playerid` smallint(5) unsigned NOT NULL,
  `autoselect` tinyint(1) unsigned NOT NULL,
  `movieurls` mediumtext NOT NULL,
  `hits` int(10) unsigned NOT NULL default '0',
  `comments` int(10) unsigned NOT NULL default '0',
  `totalview` int(10) unsigned NOT NULL default '0',
  `todayview` int(10) unsigned NOT NULL default '0',
  `weekview` int(10) unsigned NOT NULL default '0',
  `monthview` int(10) unsigned NOT NULL default '0',
  `bigthumb` varchar(255) NOT NULL,
  `thumb` varchar(255) NOT NULL default '',
  `username` varchar(20) NOT NULL default '',
  `addtime` int(10) unsigned NOT NULL default '0',
  `editor` varchar(25) NOT NULL default '',
  `edittime` int(10) unsigned NOT NULL default '0',
  `checker` varchar(25) NOT NULL default '',
  `checktime` int(10) unsigned NOT NULL default '0',
  `templateid` varchar(20) NOT NULL default '0',
  `skinid` varchar(20) NOT NULL default '0',
  `stars` tinyint(1) NOT NULL default '0',
  `serialization` tinyint(1) unsigned NOT NULL default '0',
  `arrposid` varchar(50) NOT NULL default '',
  `status` tinyint(1) NOT NULL default '0',
  `listorder` smallint(4) unsigned NOT NULL default '0',
  `arrgroupidview` varchar(255) NOT NULL default '',
  `readpoint` smallint(5) unsigned NOT NULL default '0',
  `ishtml` tinyint(1) unsigned NOT NULL default '1',
  `htmldir` varchar(20) NOT NULL default '',
  `prefix` varchar(50) NOT NULL default '',
  `urlruleid` tinyint(3) unsigned NOT NULL default '0',
  `islink` tinyint(1) unsigned NOT NULL default '0',
  `linkurl` varchar(255) NOT NULL default '',
  `lastviewtime` int(10) NOT NULL,
  PRIMARY KEY  (`movieid`),
  KEY `typeid` (`typeid`,`catid`,`status`,`listorder`,`movieid`),
  KEY `username` (`username`(10)),
  KEY `catid` (`catid`,`listorder`,`status`,`movieid`),
  KEY `hits` (`hits`,`movieid`,`status`)
) TYPE=MyISAM;