<?php
return array (
    'userid' => 
  array (
    'fieldid' => '1',
    'modelid' => '10',
    'field' => 'userid',
    'name' => '用户名',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'username',
    'setting' => '',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '1',
    'issystem' => '1',
    'isunique' => '0',
    'issearch' => '1',
    'isselect' => '1',
    'iswhere' => '1',
    'isorder' => '1',
    'islist' => '1',
    'isshow' => '1',
    'listorder' => '0',
    'disabled' => '0',
  ),
    'ip' => 
  array (
    'fieldid' => '1',
    'modelid' => '10',
    'field' => 'ip',
    'name' => 'IP地址',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => '',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '1',
    'issystem' => '1',
    'isunique' => '0',
    'issearch' => '1',
    'isselect' => '1',
    'iswhere' => '1',
    'isorder' => '1',
    'islist' => '1',
    'isshow' => '1',
    'listorder' => '0',
    'disabled' => '0',
  ),
);
?>