<?php
$tags_config = array (
  '当天总列表' => 
  array (
    'func' => 'digg_list',
    'introduce' => '',
    'page_on' => '1',
    'list_num' => '10',
    'title_text' => '70',
    'text_num' => '90',
    'index_on' => '0',
    'digg_channelid' => '0',
    'digg_catid' => '0',
    'digg_defind' => '1',
    'comment_on' => '1',
    'hits_on' => '1',
    'templateid' => 'tag_digg_list-day',
    'edittime' => '2008-01-25 10:32:37',
    'editor' => 'phpcms',
    'longtag' => 'digg_list(10,70,90,0,1,\'tag_digg_list-day\',0,1,1,1,0)',
  ),
  '本周总列表' => 
  array (
    'func' => 'digg_list',
    'introduce' => '',
    'page_on' => '0',
    'list_num' => '10',
    'title_text' => '25',
    'text_num' => '0',
    'index_on' => '0',
    'digg_channelid' => '0',
    'digg_catid' => '0',
    'digg_defind' => '7',
    'comment_on' => '0',
    'hits_on' => '0',
    'templateid' => 'tag_digg_list-week',
    'edittime' => '2008-01-23 11:40:36',
    'editor' => 'phpcms',
    'longtag' => 'digg_list(10,25,0,0,7,\'tag_digg_list-week\',0,0,0,0,0)',
  ),
  '本月总列表' => 
  array (
    'func' => 'digg_list',
    'introduce' => '',
    'page_on' => '0',
    'list_num' => '10',
    'title_text' => '25',
    'text_num' => '230',
    'index_on' => '0',
    'digg_channelid' => '0',
    'digg_catid' => '0',
    'digg_defind' => '30',
    'comment_on' => '0',
    'hits_on' => '0',
    'templateid' => 'tag_digg_list-mon',
    'edittime' => '2008-01-25 10:32:47',
    'editor' => 'phpcms',
    'longtag' => 'digg_list(10,25,230,0,30,\'tag_digg_list-mon\',0,0,0,0,0)',
  ),
  '本周文章DIGG列表' => 
  array (
    'func' => 'digg_list',
    'introduce' => '',
    'page_on' => '0',
    'list_num' => '9',
    'title_text' => '34',
    'text_num' => '0',
    'index_on' => '0',
    'digg_channelid' => '1',
    'digg_catid' => '0',
    'digg_defind' => '7',
    'comment_on' => '0',
    'hits_on' => '0',
    'templateid' => 'tag_digg_list',
    'edittime' => '2008-01-23 11:40:27',
    'editor' => 'phpcms',
    'longtag' => 'digg_list(9,34,0,0,7,\'tag_digg_list\',1,0,0,0,0)',
  ),
  '本月文章DIGG列表' => 
  array (
    'func' => 'digg_list',
    'introduce' => '',
    'page_on' => '0',
    'list_num' => '10',
    'title_text' => '25',
    'text_num' => '230',
    'index_on' => '0',
    'digg_channelid' => '1',
    'digg_catid' => '0',
    'digg_defind' => '30',
    'comment_on' => '0',
    'hits_on' => '0',
    'templateid' => 'tag_digg_list',
    'edittime' => '2008-01-23 11:40:22',
    'editor' => 'phpcms',
    'longtag' => 'digg_list(10,25,230,0,30,\'tag_digg_list\',1,0,0,0,0)',
  ),
  '今日文章DIGG列表' => 
  array (
    'func' => 'digg_list',
    'introduce' => '',
    'page_on' => '0',
    'list_num' => '10',
    'title_text' => '38',
    'text_num' => '0',
    'index_on' => '0',
    'digg_channelid' => '1',
    'digg_catid' => '0',
    'digg_defind' => '1',
    'comment_on' => '0',
    'hits_on' => '0',
    'templateid' => 'tag_digg_list',
    'edittime' => '2008-01-23 11:40:18',
    'editor' => 'phpcms',
    'longtag' => 'digg_list(10,38,0,0,1,\'tag_digg_list\',1,0,0,0,0)',
  ),
  '点击标签样式二' => 
  array (
    'func' => 'digg_add',
    'introduce' => '点击标签样式二',
    'digg_on' => '1',
    'digg_down_on' => '1',
    'style' => '2',
    'edittime' => '2008-01-11 09:30:00',
    'editor' => 'phpcms',
    'longtag' => 'digg_add(1,1,2)',
  ),
  '点击标签样式一' => 
  array (
    'func' => 'digg_add',
    'introduce' => '点击标签样式一',
    'digg_on' => '1',
    'digg_down_on' => '1',
    'style' => '1',
    'edittime' => '2007-12-28 10:36:17',
    'editor' => 'phpcms',
    'longtag' => 'digg_add(1,1,1)',
  ),
  '本周下载DIGG列表' => 
  array (
    'func' => 'digg_list',
    'introduce' => '',
    'page_on' => '0',
    'list_num' => '10',
    'title_text' => '25',
    'text_num' => '0',
    'digg_channelid' => '3',
    'digg_catid' => '0',
    'digg_defind' => '7',
    'comment_on' => '0',
    'hits_on' => '0',
    'templateid' => '0',
    'edittime' => '2008-01-16 04:16:54',
    'editor' => 'phpcms',
    'longtag' => 'digg_list(10,25,0,0,7,0,3,0,0,0)',
  ),
  '今日下载DIGG列表' => 
  array (
    'func' => 'digg_list',
    'introduce' => '',
    'page_on' => '0',
    'list_num' => '10',
    'title_text' => '25',
    'text_num' => '0',
    'index_on' => '0',
    'digg_channelid' => '3',
    'digg_catid' => '0',
    'digg_defind' => '1',
    'comment_on' => '0',
    'hits_on' => '0',
    'templateid' => '0',
    'edittime' => '2008-01-25 08:46:37',
    'editor' => 'phpcms',
    'longtag' => 'digg_list(10,25,0,0,1,0,3,0,0,0,0)',
  ),
  '今日图片DIGG列表' => 
  array (
    'func' => 'digg_list',
    'introduce' => '',
    'page_on' => '0',
    'list_num' => '7',
    'title_text' => '36',
    'text_num' => '0',
    'index_on' => '0',
    'digg_channelid' => '2',
    'digg_catid' => '0',
    'digg_defind' => '1',
    'comment_on' => '0',
    'hits_on' => '0',
    'templateid' => '0',
    'edittime' => '2008-01-23 11:40:08',
    'editor' => 'phpcms',
    'longtag' => 'digg_list(7,36,0,0,1,0,2,0,0,0,0)',
  ),
  '本周图片DIGG列表' => 
  array (
    'func' => 'digg_list',
    'introduce' => '',
    'page_on' => '0',
    'list_num' => '10',
    'title_text' => '25',
    'text_num' => '0',
    'index_on' => '0',
    'digg_channelid' => '2',
    'digg_catid' => '0',
    'digg_defind' => '7',
    'comment_on' => '0',
    'hits_on' => '0',
    'templateid' => '0',
    'edittime' => '2008-01-23 11:40:03',
    'editor' => 'phpcms',
    'longtag' => 'digg_list(10,25,0,0,7,0,2,0,0,0,0)',
  ),
  '今日影视DIGG列表' => 
  array (
    'func' => 'digg_list',
    'introduce' => '',
    'page_on' => '0',
    'list_num' => '10',
    'title_text' => '25',
    'text_num' => '0',
    'index_on' => '0',
    'digg_channelid' => '5',
    'digg_catid' => '0',
    'digg_defind' => '1',
    'comment_on' => '0',
    'hits_on' => '0',
    'templateid' => '0',
    'edittime' => '2008-01-23 11:39:58',
    'editor' => 'phpcms',
    'longtag' => 'digg_list(10,25,0,0,1,0,5,0,0,0,0)',
  ),
  '本周影视DIGG列表' => 
  array (
    'func' => 'digg_list',
    'introduce' => '',
    'page_on' => '0',
    'list_num' => '10',
    'title_text' => '25',
    'text_num' => '0',
    'index_on' => '0',
    'digg_channelid' => '5',
    'digg_catid' => '0',
    'digg_defind' => '7',
    'comment_on' => '0',
    'hits_on' => '0',
    'templateid' => '0',
    'edittime' => '2008-01-23 11:39:49',
    'editor' => 'phpcms',
    'longtag' => 'digg_list(10,25,0,0,7,0,5,0,0,0,0)',
  ),
  '首页DIGG文章排行' => 
  array (
    'func' => 'digg_list',
    'introduce' => '',
    'page_on' => '0',
    'list_num' => '5',
    'title_text' => '25',
    'text_num' => '76',
    'index_on' => '1',
    'digg_channelid' => '1',
    'digg_catid' => '0',
    'digg_defind' => '3',
    'comment_on' => '1',
    'hits_on' => '1',
    'templateid' => 'tag_digg_list-hits',
    'edittime' => '2008-01-23 11:39:44',
    'editor' => 'phpcms',
    'longtag' => 'digg_list(5,25,76,0,3,\'tag_digg_list-hits\',1,0,1,1,1)',
  ),
  '点击标签样式三' => 
  array (
    'func' => 'digg_add',
    'introduce' => '点击标签样式三',
    'digg_on' => '1',
    'digg_down_on' => '1',
    'style' => '3',
    'edittime' => '2008-01-13 09:22:07',
    'editor' => 'panda',
    'longtag' => 'digg_add(1,1,3)',
  ),
);
?>