<?php
$tags_config = array (
  '当天总列表' => 
  array (
    'func' => 'digg_list',
    'introduce' => '',
    'page_on' => '1',
    'list_num' => '8',
    'title_text' => '70',
    'text_num' => '90',
    'digg_channelid' => '0',
    'digg_catid' => '0',
    'digg_defind' => '1',
    'comment_on' => '1',
    'hits_on' => '1',
    'templateid' => 'tag_digg_list-day',
    'edittime' => '2008-01-15 11:09:17',
    'editor' => 'phpcms',
    'longtag' => 'digg_list(8,70,90,0,1,\'tag_digg_list-day\',0,1,1,1)',
  ),
  '本周总列表' => 
  array (
    'func' => 'digg_list',
    'introduce' => '本周总列表',
    'page_on' => '1',
    'list_num' => '10',
    'title_text' => '25',
    'text_num' => '0',
    'digg_channelid' => '0',
    'digg_catid' => '0',
    'digg_defind' => '7',
    'comment_on' => '0',
    'hits_on' => '0',
    'templateid' => 'tag_digg_list-week',
    'edittime' => '2007-12-25 11:47:44',
    'editor' => 'phpcms',
    'longtag' => 'digg_list(10,25,0,0,2,\'tag_digg_list-week\',0,1,0,0)',
  ),
  '本月总列表' => 
  array (
    'func' => 'digg_list',
    'introduce' => '本月总列表',
    'page_on' => '0',
    'list_num' => '10',
    'title_text' => '25',
    'text_num' => '230',
    'digg_channelid' => '0',
    'digg_catid' => '0',
    'digg_defind' => '30',
    'comment_on' => '0',
    'hits_on' => '0',
    'templateid' => 'tag_digg_list-mon',
    'edittime' => '2007-12-25 11:48:19',
    'editor' => 'phpcms',
    'longtag' => 'digg_list(10,25,230,0,3,\'tag_digg_list-mon\',0,0,0,0)',
  ),
  '本周文章DIGG列表' => 
  array (
    'func' => 'digg_list',
    'introduce' => '',
    'page_on' => '0',
    'list_num' => '9',
    'title_text' => '34',
    'text_num' => '0',
    'digg_channelid' => '7',
    'digg_catid' => '7',
    'digg_defind' => '7',
    'comment_on' => '0',
    'hits_on' => '0',
    'templateid' => 'tag_digg_list',
    'edittime' => '2008-01-12 07:46:38',
    'editor' => 'phpcms',
    'longtag' => 'digg_list(9,34,0,7,7,\'tag_digg_list\',7,0,0,0)',
  ),
  '本月文章DIGG列表' => 
  array (
    'func' => 'digg_list',
    'introduce' => '',
    'page_on' => '0',
    'list_num' => '10',
    'title_text' => '25',
    'text_num' => '230',
    'digg_channelid' => '1',
    'digg_catid' => '0',
    'digg_defind' => '30',
    'comment_on' => '0',
    'hits_on' => '0',
    'templateid' => 'tag_digg_list',
    'edittime' => '2007-12-28 01:49:21',
    'editor' => 'phpcms',
    'longtag' => 'digg_list(10,25,230,0,30,\'tag_digg_list\',1,0,0,0)',
  ),
  '今日文章DIGG列表' => 
  array (
    'func' => 'digg_list',
    'introduce' => '',
    'page_on' => '0',
    'list_num' => '8',
    'title_text' => '38',
    'text_num' => '0',
    'index_on' => '0',
    'digg_channelid' => '1',
    'digg_catid' => '0',
    'digg_defind' => '1',
    'comment_on' => '0',
    'hits_on' => '0',
    'templateid' => 'tag_digg_list',
    'edittime' => '2008-01-31 04:47:11',
    'editor' => 'phpcms',
    'longtag' => 'digg_list(8,38,0,0,1,\'tag_digg_list\',1,0,0,0,0)',
  ),
  '点击标签样式二' => 
  array (
    'func' => 'digg_add',
    'introduce' => '点击标签样式二',
    'digg_on' => '1',
    'digg_down_on' => '1',
    'style' => '2',
    'edittime' => '2008-01-11 09:30:00',
    'editor' => 'phpcms',
    'longtag' => 'digg_add(1,1,2)',
  ),
  '点击标签样式一' => 
  array (
    'func' => 'digg_add',
    'introduce' => '点击标签样式一',
    'digg_on' => '1',
    'digg_down_on' => '1',
    'style' => '1',
    'edittime' => '2007-12-28 10:36:17',
    'editor' => 'phpcms',
    'longtag' => 'digg_add(1,1,1)',
  ),
  '本周下载DIGG列表' => 
  array (
    'func' => 'digg_list',
    'introduce' => '',
    'page_on' => '0',
    'list_num' => '10',
    'title_text' => '25',
    'text_num' => '0',
    'digg_channelid' => '3',
    'digg_catid' => '0',
    'digg_defind' => '7',
    'comment_on' => '0',
    'hits_on' => '0',
    'templateid' => '0',
    'edittime' => '2007-12-29 08:45:25',
    'editor' => 'phpcms',
    'longtag' => 'digg_list(10,25,0,0,7,0,3,0,0,0)',
  ),
  '今日下载DIGG列表' => 
  array (
    'func' => 'digg_list',
    'introduce' => '',
    'page_on' => '0',
    'list_num' => '10',
    'title_text' => '25',
    'text_num' => '0',
    'digg_channelid' => '3',
    'digg_catid' => '0',
    'digg_defind' => '1',
    'comment_on' => '0',
    'hits_on' => '0',
    'templateid' => '0',
    'edittime' => '2007-12-29 08:45:32',
    'editor' => 'phpcms',
    'longtag' => 'digg_list(10,25,0,0,1,0,3,0,0,0)',
  ),
  '今日图片DIGG列表' => 
  array (
    'func' => 'digg_list',
    'introduce' => '',
    'page_on' => '0',
    'list_num' => '10',
    'title_text' => '25',
    'text_num' => '0',
    'digg_channelid' => '2',
    'digg_catid' => '0',
    'digg_defind' => '1',
    'comment_on' => '0',
    'hits_on' => '0',
    'templateid' => '0',
    'edittime' => '2007-12-29 08:52:17',
    'editor' => 'phpcms',
    'longtag' => 'digg_list(10,25,0,0,1,0,2,0,0,0)',
  ),
  '本周图片DIGG列表' => 
  array (
    'func' => 'digg_list',
    'introduce' => '',
    'page_on' => '0',
    'list_num' => '10',
    'title_text' => '25',
    'text_num' => '0',
    'digg_channelid' => '2',
    'digg_catid' => '0',
    'digg_defind' => '7',
    'comment_on' => '0',
    'hits_on' => '0',
    'templateid' => '0',
    'edittime' => '2007-12-29 08:53:09',
    'editor' => 'phpcms',
    'longtag' => 'digg_list(10,25,0,0,7,0,2,0,0,0)',
  ),
  '今日影视DIGG列表' => 
  array (
    'func' => 'digg_list',
    'introduce' => '',
    'page_on' => '0',
    'list_num' => '10',
    'title_text' => '25',
    'text_num' => '0',
    'digg_channelid' => '5',
    'digg_catid' => '0',
    'digg_defind' => '1',
    'comment_on' => '0',
    'hits_on' => '0',
    'templateid' => '0',
    'edittime' => '2007-12-29 08:59:45',
    'editor' => 'phpcms',
    'longtag' => 'digg_list(10,25,0,0,1,0,5,0,0,0)',
  ),
  '本周影视DIGG列表' => 
  array (
    'func' => 'digg_list',
    'introduce' => '',
    'page_on' => '0',
    'list_num' => '10',
    'title_text' => '25',
    'text_num' => '0',
    'digg_channelid' => '5',
    'digg_catid' => '0',
    'digg_defind' => '7',
    'comment_on' => '0',
    'hits_on' => '0',
    'templateid' => '0',
    'edittime' => '2007-12-29 08:56:17',
    'editor' => 'phpcms',
    'longtag' => 'digg_list(10,25,0,0,7,0,5,0,0,0)',
  ),
  '首页文章周排行' => 
  array (
    'func' => 'digg_list',
    'introduce' => '',
    'page_on' => '0',
    'list_num' => '3',
    'title_text' => '25',
    'text_num' => '76',
    'digg_channelid' => '7',
    'digg_catid' => '0',
    'digg_defind' => '7',
    'comment_on' => '1',
    'hits_on' => '1',
    'templateid' => 'tag_digg_list-hits',
    'edittime' => '2008-01-12 11:20:34',
    'editor' => 'phpcms',
    'longtag' => 'digg_list(3,25,76,0,7,\'tag_digg_list-hits\',7,0,1,1)',
  ),
  '首页DIGG文章排行' => 
  array (
    'func' => 'digg_list',
    'introduce' => '',
    'page_on' => '0',
    'list_num' => '5',
    'title_text' => '25',
    'text_num' => '76',
    'digg_channelid' => '7',
    'digg_catid' => '0',
    'digg_defind' => '3',
    'comment_on' => '1',
    'hits_on' => '1',
    'templateid' => 'tag_digg_list-hits',
    'edittime' => '2008-01-13 09:29:30',
    'editor' => 'phpcms',
    'longtag' => 'digg_list(5,25,76,0,3,\'tag_digg_list-hits\',7,0,1,1)',
  ),
  '点击标签样式三' => 
  array (
    'func' => 'digg_add',
    'introduce' => '点击标签样式三',
    'digg_on' => '1',
    'digg_down_on' => '1',
    'style' => '3',
    'edittime' => '2008-01-13 09:22:07',
    'editor' => 'panda',
    'longtag' => 'digg_add(1,1,3)',
  ),
);
?>