<?php
 return array (
  'comment/smilies/smile_01.gif' => '0',
  'comment/smilies/smile_02.gif' => '0',
  'comment/smilies/smile_03.gif' => '0',
  'comment/smilies/smile_04.gif' => '0',
  'comment/smilies/smile_05.gif' => '0',
  'comment/smilies/smile_06.gif' => '0',
  'comment/smilies/smile_07.gif' => '0',
  'comment/smilies/smile_08.gif' => '0',
  'comment/smilies/smile_09.gif' => '0',
  'comment/smilies/smile_10.gif' => '0',
  'comment/smilies/smile_11.gif' => '0',
  'comment/smilies/smile_12.gif' => '0',
  'comment/smilies/smile_13.gif' => '0',
  'comment/smilies/smile_14.gif' => '0',
  'comment/smilies/smile_15.gif' => '0',
  'comment/smilies/smile_16.gif' => '0',
  'comment/smilies/smile_17.gif' => '0',
  'comment/smilies/smile_18.gif' => '0',
  'comment/smilies/smile_19.gif' => '0',
  'comment/smilies/smile_20.gif' => '0',
  'comment/smilies/smile_21.gif' => '0',
  'comment/smilies/smile_22.gif' => '0',
  'comment/smilies/smile_23.gif' => '0',
  'comment/smilies/smile_24.gif' => '0',
  'comment/smilies/smile_25.gif' => '0',
  'comment/smilies/smile_26.gif' => '0',
  'comment/smilies/smile_27.gif' => '0',
  'comment/smilies/smile_28.gif' => '0',
);
?>