<?php
$tags_config = array (
  '专题幻灯片' => 
  array (
    'func' => 'phpcms_special_slide',
    'introduce' => '',
    'keyid' => '1',
    'specialnum' => '5',
    'specialnamelen' => '24',
    'iselite' => '0',
    'datenum' => '30',
    'imgwidth' => '250',
    'imgheight' => '220',
    'timeout' => '5000',
    'effectid' => '-1',
    'templateid' => '0',
    'edittime' => '2007-02-08 03:48:33',
    'editor' => 'phpcms',
    'longtag' => 'phpcms_special_slide(0,1,5,24,0,30,250,220,5000,-1)',
  ),
  '类别导航' => 
  array (
    'func' => 'phpcms_type',
    'introduce' => '',
    'keyid' => '$keyid',
    'templateid' => '0',
    'edittime' => '2007-01-14 11:42:30',
    'editor' => 'phpcms',
    'longtag' => 'phpcms_type(0,$keyid)',
  ),
  '文章专题列表' => 
  array (
    'func' => 'phpcms_special_list',
    'introduce' => '',
    'keyid' => '$channelid',
    'page' => '$page',
    'specialnum' => '10',
    'specialnamelen' => '94',
    'descriptionlen' => '320',
    'iselite' => '0',
    'datenum' => '0',
    'showtype' => '3',
    'imgwidth' => '100',
    'imgheight' => '100',
    'cols' => '1',
    'templateid' => 'tag_special_list-splist',
    'edittime' => '2008-01-13 12:03:10',
    'editor' => 'test',
    'longtag' => 'phpcms_special_list(\'tag_special_list-splist\',$channelid,$page,10,94,320,0,0,3,100,100,1)',
  ),
  '文章推荐专题' => 
  array (
    'func' => 'phpcms_special_list',
    'introduce' => '',
    'keyid' => '$channelid',
    'page' => '0',
    'specialnum' => '5',
    'specialnamelen' => '16',
    'descriptionlen' => '0',
    'iselite' => '1',
    'datenum' => '0',
    'showtype' => '4',
    'imgwidth' => '116',
    'imgheight' => '80',
    'cols' => '1',
    'templateid' => 'tag_special_list-imgtj',
    'edittime' => '2008-01-13 09:33:11',
    'editor' => 'test',
    'longtag' => 'phpcms_special_list(\'tag_special_list-imgtj\',$channelid,0,5,16,0,1,0,4,116,80,1)',
  ),
  '下载专题列表' => 
  array (
    'func' => 'phpcms_special_list',
    'introduce' => '',
    'keyid' => '$channelid',
    'page' => '$page',
    'specialnum' => '10',
    'specialnamelen' => '50',
    'descriptionlen' => '200',
    'iselite' => '0',
    'datenum' => '0',
    'showtype' => '3',
    'imgwidth' => '150',
    'imgheight' => '150',
    'cols' => '1',
    'templateid' => '0',
    'edittime' => '2007-01-15 05:16:23',
    'editor' => 'phpcms',
    'longtag' => 'phpcms_special_list(0,$channelid,$page,10,50,200,0,0,3,150,150,1)',
  ),
  '下载推荐专题' => 
  array (
    'func' => 'phpcms_special_list',
    'introduce' => '',
    'keyid' => '$channelid',
    'page' => '0',
    'specialnum' => '10',
    'specialnamelen' => '50',
    'descriptionlen' => '200',
    'iselite' => '1',
    'datenum' => '0',
    'showtype' => '4',
    'imgwidth' => '100',
    'imgheight' => '100',
    'cols' => '1',
    'templateid' => '0',
    'edittime' => '2007-01-15 05:17:51',
    'editor' => 'phpcms',
    'longtag' => 'phpcms_special_list(0,$channelid,0,10,50,200,1,0,4,100,100,1)',
  ),
  '图片专题列表' => 
  array (
    'func' => 'phpcms_special_list',
    'introduce' => '',
    'keyid' => '$channelid',
    'page' => '$page',
    'specialnum' => '10',
    'specialnamelen' => '50',
    'descriptionlen' => '200',
    'iselite' => '0',
    'datenum' => '0',
    'showtype' => '3',
    'imgwidth' => '150',
    'imgheight' => '150',
    'cols' => '1',
    'templateid' => '0',
    'edittime' => '2007-01-15 05:16:53',
    'editor' => 'phpcms',
    'longtag' => 'phpcms_special_list(0,$channelid,$page,10,50,200,0,0,3,150,150,1)',
  ),
  '图片推荐专题' => 
  array (
    'func' => 'phpcms_special_list',
    'introduce' => '',
    'keyid' => '$channelid',
    'page' => '0',
    'specialnum' => '10',
    'specialnamelen' => '50',
    'descriptionlen' => '200',
    'iselite' => '1',
    'datenum' => '0',
    'showtype' => '4',
    'imgwidth' => '100',
    'imgheight' => '100',
    'cols' => '1',
    'templateid' => '0',
    'edittime' => '2007-01-15 05:17:36',
    'editor' => 'phpcms',
    'longtag' => 'phpcms_special_list(0,$channelid,0,10,50,200,1,0,4,100,100,1)',
  ),
  '信息专题列表' => 
  array (
    'func' => 'phpcms_special_list',
    'introduce' => '',
    'keyid' => '$channelid',
    'page' => '$page',
    'specialnum' => '10',
    'specialnamelen' => '50',
    'descriptionlen' => '200',
    'iselite' => '0',
    'datenum' => '0',
    'showtype' => '4',
    'imgwidth' => '150',
    'imgheight' => '150',
    'cols' => '1',
    'templateid' => 'tag_special_list',
    'edittime' => '2008-01-06 04:37:29',
    'editor' => 'phpcms',
    'longtag' => 'phpcms_special_list(\'tag_special_list\',$channelid,$page,10,50,200,0,0,4,150,150,1)',
  ),
  '信息推荐专题' => 
  array (
    'func' => 'phpcms_special_list',
    'introduce' => '',
    'keyid' => '$channelid',
    'page' => '0',
    'specialnum' => '10',
    'specialnamelen' => '50',
    'descriptionlen' => '200',
    'iselite' => '1',
    'datenum' => '0',
    'showtype' => '4',
    'imgwidth' => '100',
    'imgheight' => '100',
    'cols' => '1',
    'templateid' => '0',
    'edittime' => '2007-01-15 05:19:19',
    'editor' => 'phpcms',
    'longtag' => 'phpcms_special_list(0,$channelid,0,10,50,200,1,0,4,100,100,1)',
  ),
  '文章频道首页专题列表' => 
  array (
    'func' => 'phpcms_special_list',
    'introduce' => '',
    'keyid' => '7',
    'page' => '0',
    'specialnum' => '1',
    'specialnamelen' => '24',
    'descriptionlen' => '184',
    'iselite' => '1',
    'datenum' => '0',
    'showtype' => '3',
    'imgwidth' => '94',
    'imgheight' => '65',
    'cols' => '1',
    'templateid' => 'tag_special_list',
    'edittime' => '2008-01-14 03:18:15',
    'editor' => 'test',
    'longtag' => 'phpcms_special_list(\'tag_special_list\',7,0,1,24,184,1,0,3,94,65,1)',
  ),
  '频道一级栏目' => 
  array (
    'func' => 'phpcms_cat',
    'introduce' => '',
    'keyid' => '$channelid',
    'catid' => '0',
    'child' => '1',
    'open' => '1',
    'showtype' => '2',
    'templateid' => 'tag_cat-1',
    'edittime' => '2007-01-15 06:34:39',
    'editor' => 'phpcms',
    'longtag' => 'phpcms_cat(\'tag_cat-1\',$channelid,0,1,2,1)',
  ),
  '频道子栏目列表' => 
  array (
    'func' => 'phpcms_cat',
    'introduce' => '',
    'keyid' => '$channelid',
    'catid' => '$catid',
    'child' => '1',
    'open' => '1',
    'showtype' => '2',
    'templateid' => 'tag_cat-sub',
    'edittime' => '2007-01-15 06:34:55',
    'editor' => 'phpcms',
    'longtag' => 'phpcms_cat(\'tag_cat-sub\',$channelid,$catid,1,2,1)',
  ),
  '下载频道首页专题' => 
  array (
    'func' => 'phpcms_special_list',
    'introduce' => '',
    'keyid' => '$channelid',
    'page' => '0',
    'specialnum' => '1',
    'specialnamelen' => '30',
    'descriptionlen' => '200',
    'iselite' => '0',
    'datenum' => '0',
    'showtype' => '4',
    'imgwidth' => '60',
    'imgheight' => '60',
    'cols' => '1',
    'templateid' => '0',
    'edittime' => '2007-01-17 03:57:21',
    'editor' => 'phpcms',
    'longtag' => 'phpcms_special_list(0,$channelid,0,1,30,200,0,0,4,60,60,1)',
  ),
  '图片频道首页专题' => 
  array (
    'func' => 'phpcms_special_list',
    'introduce' => '',
    'keyid' => '$channelid',
    'page' => '0',
    'specialnum' => '8',
    'specialnamelen' => '46',
    'descriptionlen' => '0',
    'iselite' => '0',
    'datenum' => '0',
    'showtype' => '6',
    'imgwidth' => '60',
    'imgheight' => '60',
    'cols' => '1',
    'templateid' => 'tag_special_list-ztmc',
    'edittime' => '2008-01-12 01:54:50',
    'editor' => 'xuewang',
    'longtag' => 'phpcms_special_list(\'tag_special_list-ztmc\',$channelid,0,8,46,0,0,0,6,60,60,1)',
  ),
  '模块一级栏目' => 
  array (
    'func' => 'phpcms_cat',
    'introduce' => '',
    'keyid' => '$mod',
    'catid' => '0',
    'child' => '1',
    'open' => '1',
    'showtype' => '2',
    'templateid' => 'tag_cat-1',
    'edittime' => '2007-01-15 06:34:47',
    'editor' => 'phpcms',
    'longtag' => 'phpcms_cat(\'tag_cat-1\',$mod,0,1,2,1)',
  ),
  '模块子栏目列表' => 
  array (
    'func' => 'phpcms_cat',
    'introduce' => '',
    'keyid' => '$mod',
    'catid' => '$catid',
    'child' => '1',
    'open' => '1',
    'showtype' => '2',
    'templateid' => 'tag_cat-sub',
    'edittime' => '2007-01-15 06:36:54',
    'editor' => 'phpcms',
    'longtag' => 'phpcms_cat(\'tag_cat-sub\',$mod,$catid,1,2,1)',
  ),
  '网站首页推荐专题' => 
  array (
    'func' => 'phpcms_special_list',
    'introduce' => '',
    'keyid' => '1',
    'page' => '0',
    'specialnum' => '1',
    'specialnamelen' => '34',
    'descriptionlen' => '100',
    'iselite' => '1',
    'datenum' => '0',
    'showtype' => '4',
    'imgwidth' => '80',
    'imgheight' => '100',
    'cols' => '1',
    'templateid' => '0',
    'edittime' => '2007-02-09 09:58:46',
    'editor' => 'phpcms',
    'longtag' => 'phpcms_special_list(0,1,0,2,34,100,1,30,4,80,100,1)',
  ),
  '首页幻灯片' => 
  array (
    'type' => '首页幻灯片',
    'func' => 'phpcms_freelink',
    'keyid' => 'phpcms',
    'edittime' => '2008-01-16 01:56:53',
    'editor' => 'phpcms',
    'longtag' => 'phpcms_freelink(\'首页幻灯片\')',
  ),
  '首页推荐信息' => 
  array (
    'type' => '首页推荐信息',
    'func' => 'phpcms_freelink',
    'keyid' => 'phpcms',
    'edittime' => '2008-01-12 05:30:50',
    'editor' => 'phpcms',
    'longtag' => 'phpcms_freelink(\'首页推荐信息\')',
  ),
  '影片频道首页专题' => 
  array (
    'func' => 'phpcms_special_list',
    'introduce' => '',
    'keyid' => '$channelid',
    'page' => '0',
    'specialnum' => '1',
    'specialnamelen' => '30',
    'descriptionlen' => '200',
    'iselite' => '0',
    'datenum' => '0',
    'showtype' => '4',
    'imgwidth' => '60',
    'imgheight' => '60',
    'cols' => '1',
    'templateid' => '0',
    'edittime' => '2007-07-31 08:50:42',
    'editor' => 'phpcmssp4',
    'longtag' => 'phpcms_special_list(0,$channelid,0,1,30,200,0,0,4,60,60,1)',
  ),
  '测试图片调用' => 
  array (
    'type' => '测试图片调用',
    'func' => 'phpcms_freelink',
    'keyid' => 'phpcms',
    'edittime' => '2007-07-31 04:09:46',
    'editor' => 'phpcmssp4',
    'longtag' => 'phpcms_freelink(\'测试图片调用\')',
  ),
  '影片推荐专题' => 
  array (
    'func' => 'phpcms_special_list',
    'introduce' => '',
    'keyid' => '$channelid',
    'page' => '0',
    'specialnum' => '10',
    'specialnamelen' => '50',
    'descriptionlen' => '200',
    'iselite' => '1',
    'datenum' => '0',
    'showtype' => '4',
    'imgwidth' => '100',
    'imgheight' => '100',
    'cols' => '1',
    'templateid' => '0',
    'edittime' => '2007-08-03 12:25:01',
    'editor' => 'phpcms',
    'longtag' => 'phpcms_special_list(0,$channelid,0,10,50,200,1,0,4,100,100,1)',
  ),
  '导航菜单循环' => 
  array (
    'func' => 'phpcms_cat',
    'introduce' => '导航菜单循环',
    'keyid' => '$tempchinnalid',
    'catid' => '0',
    'open' => '1',
    'showtype' => '2',
    'templateid' => 'tag_cat-1',
    'child' => '0',
    'edittime' => '2008-01-09 09:14:47',
    'editor' => 'phpip',
    'longtag' => 'phpcms_cat(\'tag_cat-1\',$tempchinnalid,0,0,2,1)',
  ),
  '首页推荐问吧' => 
  array (
    'type' => '首页推荐问吧',
    'func' => 'phpcms_freelink',
    'keyid' => 'phpcms',
    'edittime' => '2008-01-11 08:44:27',
    'editor' => 'test',
    'longtag' => 'phpcms_freelink(\'首页推荐问吧\')',
  ),
  '下载频道首页专题列表' => 
  array (
    'func' => 'phpcms_special_list',
    'introduce' => '',
    'keyid' => '3',
    'page' => '0',
    'specialnum' => '1',
    'specialnamelen' => '28',
    'descriptionlen' => '184',
    'iselite' => '1',
    'datenum' => '0',
    'showtype' => '3',
    'imgwidth' => '94',
    'imgheight' => '65',
    'cols' => '1',
    'templateid' => 'tag_special_list',
    'edittime' => '2008-01-12 08:05:40',
    'editor' => 'phpcms',
    'longtag' => 'phpcms_special_list(\'tag_special_list\',3,0,1,28,184,1,0,3,94,65,1)',
  ),
  '推荐专题名称列表' => 
  array (
    'func' => 'phpcms_special_list',
    'introduce' => '',
    'keyid' => '$channelid',
    'page' => '0',
    'specialnum' => '2',
    'specialnamelen' => '40',
    'descriptionlen' => '0',
    'iselite' => '1',
    'datenum' => '0',
    'showtype' => '6',
    'imgwidth' => '94',
    'imgheight' => '65',
    'cols' => '1',
    'templateid' => 'tag_special_list-ztmc',
    'edittime' => '2008-01-13 10:03:48',
    'editor' => 'phpcms',
    'longtag' => 'phpcms_special_list(\'tag_special_list-ztmc\',$channelid,0,2,40,0,1,0,6,94,65,1)',
  ),
  '文章频道专题名称列表' => 
  array (
    'func' => 'phpcms_special_list',
    'introduce' => '',
    'keyid' => '7',
    'page' => '0',
    'specialnum' => '1',
    'specialnamelen' => '24',
    'descriptionlen' => '52',
    'iselite' => '1',
    'datenum' => '0',
    'showtype' => '6',
    'imgwidth' => '94',
    'imgheight' => '65',
    'cols' => '1',
    'templateid' => 'tag_special_list-bts',
    'edittime' => '2008-01-07 11:49:48',
    'editor' => 'test',
    'longtag' => 'phpcms_special_list(\'tag_special_list-bts\',7,0,1,24,52,1,0,6,94,65,1)',
  ),
  '全站头部置顶' => 
  array (
    'type' => '全站头部置顶',
    'func' => 'phpcms_freelink',
    'keyid' => 'phpcms',
    'edittime' => '2008-01-09 11:31:25',
    'editor' => 'phpip',
    'longtag' => 'phpcms_freelink(\'全站头部置顶\')',
  ),
  '信息频道子栏目列表' => 
  array (
    'func' => 'phpcms_cat',
    'introduce' => '',
    'keyid' => '$channelid',
    'catid' => '$catid',
    'child' => '1',
    'open' => '1',
    'showtype' => '2',
    'templateid' => 'tag_cat-xxpdzlm',
    'edittime' => '2008-01-09 03:20:23',
    'editor' => 'phpcms',
    'longtag' => 'phpcms_cat(\'tag_cat-xxpdzlm\',$channelid,$catid,1,2,1)',
  ),
  '3dflash' => 
  array (
    'type' => '3dflash',
    'func' => 'phpcms_freelink',
    'keyid' => 'phpcms',
    'edittime' => '2008-01-16 01:50:57',
    'editor' => 'phpcms',
    'longtag' => 'phpcms_freelink(\'3dflash\')',
  ),
  'flash_下载频道首页' => 
  array (
    'type' => 'flash_下载频道首页',
    'func' => 'phpcms_freelink',
    'keyid' => 'phpcms',
    'edittime' => '2008-01-16 01:47:17',
    'editor' => 'phpip',
    'longtag' => 'phpcms_freelink(\'flash_下载频道首页\')',
  ),
  'flash_图片频道首页' => 
  array (
    'type' => 'flash_图片频道首页',
    'func' => 'phpcms_freelink',
    'keyid' => 'phpcms',
    'edittime' => '2008-01-16 01:51:07',
    'editor' => 'phpcms',
    'longtag' => 'phpcms_freelink(\'flash_图片频道首页\')',
  ),
  'flash_新闻频道首页' => 
  array (
    'type' => 'flash_新闻频道首页',
    'func' => 'phpcms_freelink',
    'keyid' => 'phpcms',
    'edittime' => '2008-01-16 01:51:16',
    'editor' => 'phpcms',
    'longtag' => 'phpcms_freelink(\'flash_新闻频道首页\')',
  ),
  '网站首页-黄页导航' => 
  array (
    'func' => 'phpcms_cat',
    'introduce' => '',
    'keyid' => 'yp',
    'catid' => '0',
    'child' => '1',
    'showtype' => '0',
    'open' => '1',
    'templateid' => '0',
    'edittime' => '2008-01-12 03:02:01',
    'editor' => 'phpcms',
    'longtag' => 'phpcms_cat(0,\'yp\',0,1,0,1)',
  ),
  '商城子栏目调用' => 
  array (
    'func' => 'phpcms_cat',
    'introduce' => '商城子栏目调用',
    'keyid' => '$mod',
    'catid' => '$catid',
    'child' => '1',
    'open' => '1',
    'showtype' => '2',
    'templateid' => 'tag_cat-sub-li',
    'edittime' => '2008-01-16 01:47:51',
    'editor' => 'phpip',
    'longtag' => 'phpcms_cat(\'tag_cat-sub-li\',$mod,$catid,1,2,1)',
  ),
);
?>