<?php
$tags_config = array (
  '总积分排行榜' => 
  array (
    'func' => 'credit_list',
    'introduce' => '',
    'credit_num' => '10',
    'page' => '0',
    'credit_status' => 'all',
    'datetype' => '0',
    'target' => '0',
    'cols' => '1',
    'templateid' => '0',
    'edittime' => '2007-11-23 01:15:40',
    'editor' => 'admin',
    'longtag' => 'credit_list(0,10,0,0,0,1,\'all\')',
  ),
  '热点问题' => 
  array (
    'func' => 'hotques_list',
    'introduce' => '',
    'hotques_num' => '10',
    'subjectlen' => '30',
    'target' => '0',
    'cols' => '1',
    'templateid' => '0',
    'edittime' => '2007-11-08 03:28:40',
    'editor' => 'admin',
    'longtag' => 'hotques_list(0,10,30,0,1)',
  ),
  '上月积分排行榜' => 
  array (
    'func' => 'credit_list',
    'introduce' => '',
    'credit_num' => '10',
    'page' => '0',
    'credit_status' => 'month',
    'datetype' => '1',
    'target' => '0',
    'cols' => '1',
    'templateid' => '0',
    'edittime' => '2007-11-23 01:18:13',
    'editor' => 'admin',
    'longtag' => 'credit_list(0,10,0,1,0,1,\'month\')',
  ),
  '上周积分排行榜' => 
  array (
    'func' => 'credit_list',
    'introduce' => '',
    'credit_num' => '10',
    'page' => '0',
    'credit_status' => 'week',
    'datetype' => '0',
    'target' => '0',
    'cols' => '1',
    'templateid' => '0',
    'edittime' => '2007-11-23 01:19:01',
    'editor' => 'admin',
    'longtag' => 'credit_list(0,10,0,0,0,1,\'week\')',
  ),
  '栏目页问题标签' => 
  array (
    'func' => 'question_list',
    'introduce' => '栏目页问题标签',
    'catid' => '$catid',
    'child' => '1',
    'page' => '$page',
    'ques_num' => '20',
    'subjectlen' => '60',
    'elite' => '0',
    'ques_type' => '$option',
    'showcatname' => '1',
    'datenum' => '0',
    'ordertype' => '0',
    'datetype' => '6',
    'target' => '0',
    'cols' => '1',
    'username' => '',
    'templateid' => 'tag_question_list-column',
    'edittime' => '2007-12-28 05:16:51',
    'editor' => 'phpcms',
    'longtag' => 'question_list(\'tag_question_list-column\',$catid,1,$page,20,60,0,$option,1,6,0,0,\'\',0,1)',
  ),
  '推荐的问题' => 
  array (
    'func' => 'question_list',
    'introduce' => '推荐的问题',
    'catid' => '0',
    'child' => '1',
    'page' => '0',
    'ques_num' => '10',
    'subjectlen' => '60',
    'elite' => '1',
    'ques_type' => 'all',
    'showcatname' => '1',
    'datenum' => '0',
    'ordertype' => '0',
    'datetype' => '6',
    'target' => '1',
    'cols' => '1',
    'username' => '',
    'templateid' => '0',
    'edittime' => '2007-12-28 05:16:31',
    'editor' => 'phpcms',
    'longtag' => 'question_list(0,0,1,0,10,60,1,\'all\',1,6,0,0,\'\',1,1)',
  ),
  '待解决问题' => 
  array (
    'func' => 'question_list',
    'introduce' => '待解决问题',
    'catid' => '0',
    'child' => '1',
    'page' => '0',
    'ques_num' => '10',
    'subjectlen' => '60',
    'elite' => '0',
    'ques_type' => 'nosolve',
    'showcatname' => '1',
    'datenum' => '0',
    'ordertype' => '0',
    'datetype' => '6',
    'target' => '1',
    'cols' => '1',
    'username' => '',
    'templateid' => '0',
    'edittime' => '2007-12-28 05:19:05',
    'editor' => 'phpcms',
    'longtag' => 'question_list(0,0,1,0,10,60,0,\'nosolve\',1,6,0,0,\'\',1,1)',
  ),
  '已解决问题' => 
  array (
    'func' => 'question_list',
    'introduce' => '已解决问题',
    'catid' => '0',
    'child' => '1',
    'page' => '0',
    'ques_num' => '10',
    'subjectlen' => '60',
    'elite' => '0',
    'ques_type' => 'solve',
    'showcatname' => '1',
    'datenum' => '0',
    'ordertype' => '0',
    'datetype' => '6',
    'target' => '0',
    'cols' => '1',
    'username' => '',
    'templateid' => '0',
    'edittime' => '2007-12-28 05:19:21',
    'editor' => 'phpcms',
    'longtag' => 'question_list(0,0,1,0,10,60,0,\'solve\',1,6,0,0,\'\',0,1)',
  ),
  '积分排行标签' => 
  array (
    'func' => 'credit_list',
    'introduce' => '积分排行标签',
    'credit_num' => '50',
    'page' => '$page',
    'credit_status' => '$option',
    'datetype' => '6',
    'target' => '0',
    'cols' => '1',
    'templateid' => 'tag_credit_list-detail',
    'edittime' => '2007-11-23 01:38:20',
    'editor' => 'admin',
    'longtag' => 'credit_list(\'tag_credit_list-detail\',50,$page,6,0,1,$option)',
  ),
  '栏目热点问题' => 
  array (
    'func' => 'question_list',
    'introduce' => '',
    'catid' => '$catid',
    'child' => '1',
    'page' => '0',
    'ques_num' => '10',
    'subjectlen' => '30',
    'elite' => '0',
    'ques_type' => 'all',
    'showcatname' => '0',
    'datenum' => '0',
    'ordertype' => '0',
    'datetype' => '0',
    'target' => '0',
    'cols' => '1',
    'username' => '',
    'templateid' => '0',
    'edittime' => '2007-12-28 05:19:29',
    'editor' => 'phpcms',
    'longtag' => 'question_list(0,$catid,1,0,10,30,0,\'all\',0,0,0,0,\'\',0,1)',
  ),
  '详细页面热点问题' => 
  array (
    'func' => 'question_list',
    'introduce' => '详细页面热点问题',
    'catid' => '$catid',
    'child' => '1',
    'page' => '0',
    'ques_num' => '10',
    'subjectlen' => '28',
    'elite' => '0',
    'ques_type' => 'all',
    'showcatname' => '0',
    'datenum' => '0',
    'ordertype' => '0',
    'datetype' => '0',
    'target' => '0',
    'cols' => '1',
    'username' => '',
    'templateid' => '0',
    'edittime' => '2007-12-28 05:19:36',
    'editor' => 'phpcms',
    'longtag' => 'question_list(0,$catid,1,0,10,28,0,\'all\',0,0,0,0,\'\',0,1)',
  ),
);
?>