<?php
$tags_config = array (
  '频道首页最新公告' => 
  array (
    'func' => 'announce_list',
    'introduce' => '',
    'page' => '0',
    'keyid' => '$channelid',
    'announcenum' => '5',
    'subjectlen' => '28',
    'datetype' => '0',
    'showauthor' => '0',
    'target' => '1',
    'width' => '180',
    'height' => '100',
    'templateid' => 'tag_announce_list',
    'edittime' => '2007-01-16 05:43:30',
    'editor' => 'phpcms',
    'longtag' => 'announce_list(\'tag_announce_list\',$channelid,0,5,180, 100,28,0,0,1)',
  ),
  '模块公告' => 
  array (
    'func' => 'announce_list',
    'introduce' => '',
    'page' => '0',
    'keyid' => '$mod',
    'announcenum' => '10',
    'subjectlen' => '50',
    'datetype' => '0',
    'showauthor' => '0',
    'target' => '1',
    'width' => '180',
    'height' => '100',
    'templateid' => 'tag_announce_list',
    'edittime' => '2007-01-15 08:32:20',
    'editor' => 'phpcms',
    'longtag' => 'announce_list(\'tag_announce_list\',$mod,0,10,180, 100,50,0,0,1)',
  ),
  '网站首页最新公告' => 
  array (
    'func' => 'announce_list',
    'introduce' => '',
    'page' => '0',
    'keyid' => '0',
    'announcenum' => '10',
    'subjectlen' => '50',
    'datetype' => '0',
    'showauthor' => '0',
    'target' => '1',
    'width' => '180',
    'height' => '80',
    'templateid' => '0',
    'edittime' => '2007-02-09 09:41:59',
    'editor' => 'phpcms',
    'longtag' => 'announce_list(0,0,0,10,180, 80,50,0,0,1)',
  ),
  '信息频道首页公告' => 
  array (
    'func' => 'announce_list',
    'introduce' => '',
    'page' => '0',
    'keyid' => '$channelid',
    'announcenum' => '5',
    'subjectlen' => '50',
    'datetype' => '1',
    'showauthor' => '0',
    'target' => '1',
    'width' => '500',
    'height' => '25',
    'templateid' => 'tag_announce_list-left',
    'edittime' => '2007-01-16 05:49:54',
    'editor' => 'phpcms',
    'longtag' => 'announce_list(\'tag_announce_list-left\',$channelid,0,5,500, 25,50,1,0,1)',
  ),
);
?>