<?php
$tags_config = array (
  '频道首页最新公告' => 
  array (
    'func' => 'announce_list',
    'introduce' => '',
    'page' => '0',
    'keyid' => '$channelid',
    'announcenum' => '5',
    'subjectlen' => '28',
    'datetype' => '0',
    'showauthor' => '0',
    'target' => '1',
    'width' => '180',
    'height' => '100',
    'templateid' => 'tag_announce_list',
    'edittime' => '2008-01-12 05:37:10',
    'editor' => 'phpcms',
    'longtag' => 'announce_list(\'tag_announce_list\',$channelid,0,5,180, 100,28,0,0,1)',
  ),
  '模块公告' => 
  array (
    'func' => 'announce_list',
    'introduce' => '',
    'page' => '0',
    'keyid' => '$mod',
    'announcenum' => '10',
    'subjectlen' => '50',
    'datetype' => '0',
    'showauthor' => '0',
    'target' => '1',
    'width' => '180',
    'height' => '100',
    'templateid' => 'tag_announce_list',
    'edittime' => '2007-01-15 08:32:20',
    'editor' => 'phpcms',
    'longtag' => 'announce_list(\'tag_announce_list\',$mod,0,10,180, 100,50,0,0,1)',
  ),
  '网站首页最新公告' => 
  array (
    'func' => 'announce_list',
    'introduce' => '',
    'page' => '0',
    'keyid' => '0',
    'announcenum' => '5',
    'subjectlen' => '70',
    'datetype' => '1',
    'showauthor' => '0',
    'target' => '1',
    'width' => '180',
    'height' => '80',
    'templateid' => 'tag_announce_list-sp6',
    'edittime' => '2008-01-12 05:39:06',
    'editor' => 'phpcms',
    'longtag' => 'announce_list(\'tag_announce_list-sp6\',0,0,5,180, 80,70,1,0,1)',
  ),
  '信息频道首页公告' => 
  array (
    'func' => 'announce_list',
    'introduce' => '',
    'page' => '0',
    'keyid' => '$channelid',
    'announcenum' => '5',
    'subjectlen' => '50',
    'datetype' => '1',
    'showauthor' => '0',
    'target' => '1',
    'width' => '500',
    'height' => '25',
    'templateid' => 'tag_announce_list-left',
    'edittime' => '2007-01-16 05:49:54',
    'editor' => 'phpcms',
    'longtag' => 'announce_list(\'tag_announce_list-left\',$channelid,0,5,500, 25,50,1,0,1)',
  ),
  '商城首页最新公告' => 
  array (
    'func' => 'announce_list',
    'introduce' => '商城首页最新公告',
    'page' => '0',
    'keyid' => 'product',
    'announcenum' => '3',
    'subjectlen' => '26',
    'datetype' => '0',
    'showauthor' => '0',
    'target' => '1',
    'width' => '200',
    'height' => '80',
    'templateid' => 'tag_announce_list-sp6',
    'edittime' => '2008-01-13 02:23:19',
    'editor' => 'phpcms',
    'longtag' => 'announce_list(\'tag_announce_list-sp6\',\'product\',0,3,200, 80,26,0,0,1)',
  ),
);
?>